// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AccountHolderListPageResponseTest {

    @Test
    fun create() {
        val accountHolderListPageResponse =
            AccountHolderListPageResponse.builder()
                .addData(
                    AccountHolder.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBeneficialOwnerEntity(
                            AccountHolder.AccountHolderBusinessResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dbaBusinessName("dba_business_name")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .governmentId("114-123-1513")
                                .legalBusinessName("Acme, Inc.")
                                .addPhoneNumber("+15555555555")
                                .parentCompany("parent_company")
                                .build()
                        )
                        .addBeneficialOwnerIndividual(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .businessEntity(
                            AccountHolder.AccountHolderBusinessResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dbaBusinessName("dba_business_name")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .governmentId("114-123-1513")
                                .legalBusinessName("Acme, Inc.")
                                .addPhoneNumber("+15555555555")
                                .parentCompany("parent_company")
                                .build()
                        )
                        .controlPerson(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .email("+15555555555")
                        .exemptionType(AccountHolder.ExemptionType.AUTHORIZED_USER)
                        .externalId("external_id")
                        .individual(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .naicsCode("naics_code")
                        .natureOfBusiness("nature_of_business")
                        .phoneNumber("+15555555555")
                        .addRequiredDocument(
                            RequiredDocument.builder()
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addStatusReason("string")
                                .addValidDocument("string")
                                .build()
                        )
                        .status(AccountHolder.Status.ACCEPTED)
                        .addStatusReason(AccountHolder.StatusReason.ADDRESS_VERIFICATION_FAILURE)
                        .userType(AccountHolder.UserType.BUSINESS)
                        .verificationApplication(
                            AccountHolder.AccountHolderVerificationApplication.builder()
                                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    AccountHolder.AccountHolderVerificationApplication.Status
                                        .ACCEPTED
                                )
                                .addStatusReason(
                                    AccountHolder.AccountHolderVerificationApplication.StatusReason
                                        .ADDRESS_VERIFICATION_FAILURE
                                )
                                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .websiteUrl("website_url")
                        .build()
                )
                .hasMore(true)
                .build()

        assertThat(accountHolderListPageResponse.data())
            .containsExactly(
                AccountHolder.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addBeneficialOwnerEntity(
                        AccountHolder.AccountHolderBusinessResponse.builder()
                            .address(
                                Address.builder()
                                    .address1("123 Old Forest Way")
                                    .city("Omaha")
                                    .country("USA")
                                    .postalCode("68022")
                                    .state("NE")
                                    .address2("address2")
                                    .build()
                            )
                            .dbaBusinessName("dba_business_name")
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .governmentId("114-123-1513")
                            .legalBusinessName("Acme, Inc.")
                            .addPhoneNumber("+15555555555")
                            .parentCompany("parent_company")
                            .build()
                    )
                    .addBeneficialOwnerIndividual(
                        AccountHolder.AccountHolderIndividualResponse.builder()
                            .address(
                                Address.builder()
                                    .address1("123 Old Forest Way")
                                    .city("Omaha")
                                    .country("USA")
                                    .postalCode("68022")
                                    .state("NE")
                                    .address2("address2")
                                    .build()
                            )
                            .dob("1991-03-08 08:00:00")
                            .email("tom@middle-earth.com")
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .firstName("Tom")
                            .lastName("Bombadil")
                            .phoneNumber("+15555555555")
                            .build()
                    )
                    .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .businessEntity(
                        AccountHolder.AccountHolderBusinessResponse.builder()
                            .address(
                                Address.builder()
                                    .address1("123 Old Forest Way")
                                    .city("Omaha")
                                    .country("USA")
                                    .postalCode("68022")
                                    .state("NE")
                                    .address2("address2")
                                    .build()
                            )
                            .dbaBusinessName("dba_business_name")
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .governmentId("114-123-1513")
                            .legalBusinessName("Acme, Inc.")
                            .addPhoneNumber("+15555555555")
                            .parentCompany("parent_company")
                            .build()
                    )
                    .controlPerson(
                        AccountHolder.AccountHolderIndividualResponse.builder()
                            .address(
                                Address.builder()
                                    .address1("123 Old Forest Way")
                                    .city("Omaha")
                                    .country("USA")
                                    .postalCode("68022")
                                    .state("NE")
                                    .address2("address2")
                                    .build()
                            )
                            .dob("1991-03-08 08:00:00")
                            .email("tom@middle-earth.com")
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .firstName("Tom")
                            .lastName("Bombadil")
                            .phoneNumber("+15555555555")
                            .build()
                    )
                    .email("+15555555555")
                    .exemptionType(AccountHolder.ExemptionType.AUTHORIZED_USER)
                    .externalId("external_id")
                    .individual(
                        AccountHolder.AccountHolderIndividualResponse.builder()
                            .address(
                                Address.builder()
                                    .address1("123 Old Forest Way")
                                    .city("Omaha")
                                    .country("USA")
                                    .postalCode("68022")
                                    .state("NE")
                                    .address2("address2")
                                    .build()
                            )
                            .dob("1991-03-08 08:00:00")
                            .email("tom@middle-earth.com")
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .firstName("Tom")
                            .lastName("Bombadil")
                            .phoneNumber("+15555555555")
                            .build()
                    )
                    .naicsCode("naics_code")
                    .natureOfBusiness("nature_of_business")
                    .phoneNumber("+15555555555")
                    .addRequiredDocument(
                        RequiredDocument.builder()
                            .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addStatusReason("string")
                            .addValidDocument("string")
                            .build()
                    )
                    .status(AccountHolder.Status.ACCEPTED)
                    .addStatusReason(AccountHolder.StatusReason.ADDRESS_VERIFICATION_FAILURE)
                    .userType(AccountHolder.UserType.BUSINESS)
                    .verificationApplication(
                        AccountHolder.AccountHolderVerificationApplication.builder()
                            .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .status(
                                AccountHolder.AccountHolderVerificationApplication.Status.ACCEPTED
                            )
                            .addStatusReason(
                                AccountHolder.AccountHolderVerificationApplication.StatusReason
                                    .ADDRESS_VERIFICATION_FAILURE
                            )
                            .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .websiteUrl("website_url")
                    .build()
            )
        assertThat(accountHolderListPageResponse.hasMore()).isEqualTo(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val accountHolderListPageResponse =
            AccountHolderListPageResponse.builder()
                .addData(
                    AccountHolder.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBeneficialOwnerEntity(
                            AccountHolder.AccountHolderBusinessResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dbaBusinessName("dba_business_name")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .governmentId("114-123-1513")
                                .legalBusinessName("Acme, Inc.")
                                .addPhoneNumber("+15555555555")
                                .parentCompany("parent_company")
                                .build()
                        )
                        .addBeneficialOwnerIndividual(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .businessEntity(
                            AccountHolder.AccountHolderBusinessResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dbaBusinessName("dba_business_name")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .governmentId("114-123-1513")
                                .legalBusinessName("Acme, Inc.")
                                .addPhoneNumber("+15555555555")
                                .parentCompany("parent_company")
                                .build()
                        )
                        .controlPerson(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .email("+15555555555")
                        .exemptionType(AccountHolder.ExemptionType.AUTHORIZED_USER)
                        .externalId("external_id")
                        .individual(
                            AccountHolder.AccountHolderIndividualResponse.builder()
                                .address(
                                    Address.builder()
                                        .address1("123 Old Forest Way")
                                        .city("Omaha")
                                        .country("USA")
                                        .postalCode("68022")
                                        .state("NE")
                                        .address2("address2")
                                        .build()
                                )
                                .dob("1991-03-08 08:00:00")
                                .email("tom@middle-earth.com")
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .firstName("Tom")
                                .lastName("Bombadil")
                                .phoneNumber("+15555555555")
                                .build()
                        )
                        .naicsCode("naics_code")
                        .natureOfBusiness("nature_of_business")
                        .phoneNumber("+15555555555")
                        .addRequiredDocument(
                            RequiredDocument.builder()
                                .entityToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addStatusReason("string")
                                .addValidDocument("string")
                                .build()
                        )
                        .status(AccountHolder.Status.ACCEPTED)
                        .addStatusReason(AccountHolder.StatusReason.ADDRESS_VERIFICATION_FAILURE)
                        .userType(AccountHolder.UserType.BUSINESS)
                        .verificationApplication(
                            AccountHolder.AccountHolderVerificationApplication.builder()
                                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    AccountHolder.AccountHolderVerificationApplication.Status
                                        .ACCEPTED
                                )
                                .addStatusReason(
                                    AccountHolder.AccountHolderVerificationApplication.StatusReason
                                        .ADDRESS_VERIFICATION_FAILURE
                                )
                                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .websiteUrl("website_url")
                        .build()
                )
                .hasMore(true)
                .build()

        val roundtrippedAccountHolderListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(accountHolderListPageResponse),
                jacksonTypeRef<AccountHolderListPageResponse>(),
            )

        assertThat(roundtrippedAccountHolderListPageResponse)
            .isEqualTo(accountHolderListPageResponse)
    }
}
