// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AsaRequestWebhookEventTest {

    @Test
    fun create() {
        val asaRequestWebhookEvent =
            AsaRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .authorizationAmount(0L)
                .avs(
                    AsaRequestWebhookEvent.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(AsaRequestWebhookEvent.Avs.AddressMatchResult.MATCH)
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    AsaRequestWebhookEvent.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .hostname("hostname")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            AsaRequestWebhookEvent.AsaRequestCard.SpendLimitDuration.ANNUALLY
                        )
                        .state(AsaRequestWebhookEvent.AsaRequestCard.State.CLOSED)
                        .type(AsaRequestWebhookEvent.AsaRequestCard.CardType.SINGLE_USE)
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    Merchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .settledAmount(0L)
                .status(AsaRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(AsaRequestWebhookEvent.TransactionInitiator.CARDHOLDER)
                .accountType(AsaRequestWebhookEvent.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    AsaRequestWebhookEvent.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    AsaRequestWebhookEvent.LatestChallenge.builder()
                        .phoneNumber("phone_number")
                        .status(AsaRequestWebhookEvent.LatestChallenge.Status.COMPLETED)
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .network(AsaRequestWebhookEvent.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    AsaRequestWebhookEvent.AsaNetworkSpecificData.builder()
                        .mastercard(
                            AsaRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    AsaRequestWebhookEvent.AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            AsaRequestWebhookEvent.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    AsaRequestWebhookEvent.Pos.builder()
                        .entryMode(
                            AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.builder()
                                .card(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Card.PRESENT
                                )
                                .cardholder(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY
                                )
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            AsaRequestWebhookEvent.Pos.AsaPosTerminal.builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    AsaRequestWebhookEvent.Pos.AsaPosTerminal.Operator
                                        .ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    AsaRequestWebhookEvent.Pos.AsaPosTerminal.PinCapability.CAPABLE
                                )
                                .type(AsaRequestWebhookEvent.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                                .acceptorTerminalId(" r 0K9tW")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(asaRequestWebhookEvent.token()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(asaRequestWebhookEvent.acquirerFee()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.amount()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.authorizationAmount()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.avs())
            .isEqualTo(
                AsaRequestWebhookEvent.Avs.builder()
                    .address("address")
                    .addressOnFileMatch(AsaRequestWebhookEvent.Avs.AddressMatchResult.MATCH)
                    .zipcode("zipcode")
                    .build()
            )
        assertThat(asaRequestWebhookEvent.card())
            .isEqualTo(
                AsaRequestWebhookEvent.AsaRequestCard.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .hostname("hostname")
                    .lastFour("last_four")
                    .memo("memo")
                    .spendLimit(0L)
                    .spendLimitDuration(
                        AsaRequestWebhookEvent.AsaRequestCard.SpendLimitDuration.ANNUALLY
                    )
                    .state(AsaRequestWebhookEvent.AsaRequestCard.State.CLOSED)
                    .type(AsaRequestWebhookEvent.AsaRequestCard.CardType.SINGLE_USE)
                    .build()
            )
        assertThat(asaRequestWebhookEvent.cardholderCurrency()).isEqualTo("cardholder_currency")
        assertThat(asaRequestWebhookEvent.cashAmount()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(asaRequestWebhookEvent.merchant())
            .isEqualTo(
                Merchant.builder()
                    .acceptorId("333301802529120")
                    .acquiringInstitutionId("191231")
                    .city("NEW YORK")
                    .country("USA")
                    .descriptor("COFFEE SHOP")
                    .mcc("5812")
                    .state("NY")
                    .build()
            )
        assertThat(asaRequestWebhookEvent.merchantAmount()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.merchantCurrency()).isEqualTo("USD")
        assertThat(asaRequestWebhookEvent.settledAmount()).isEqualTo(0L)
        assertThat(asaRequestWebhookEvent.status())
            .isEqualTo(AsaRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
        assertThat(asaRequestWebhookEvent.transactionInitiator())
            .isEqualTo(AsaRequestWebhookEvent.TransactionInitiator.CARDHOLDER)
        assertThat(asaRequestWebhookEvent.accountType())
            .contains(AsaRequestWebhookEvent.AccountType.CHECKING)
        assertThat(asaRequestWebhookEvent.cardholderAuthentication())
            .contains(
                CardholderAuthentication.builder()
                    .authenticationMethod(
                        CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                    )
                    .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                    .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                    .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                    .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                    .build()
            )
        assertThat(asaRequestWebhookEvent.cashback()).contains(0L)
        assertThat(asaRequestWebhookEvent.conversionRate()).contains(0.0)
        assertThat(asaRequestWebhookEvent.eventToken())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(asaRequestWebhookEvent.fleetInfo())
            .contains(
                AsaRequestWebhookEvent.AsaRequestFleetInfo.builder()
                    .fleetPromptCode(
                        AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                    )
                    .fleetRestrictionCode(
                        AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetRestrictionCode
                            .NO_RESTRICTIONS
                    )
                    .driverNumber("driver_number")
                    .vehicleNumber("vehicle_number")
                    .build()
            )
        assertThat(asaRequestWebhookEvent.latestChallenge())
            .contains(
                AsaRequestWebhookEvent.LatestChallenge.builder()
                    .phoneNumber("phone_number")
                    .status(AsaRequestWebhookEvent.LatestChallenge.Status.COMPLETED)
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(asaRequestWebhookEvent.network()).contains(AsaRequestWebhookEvent.Network.AMEX)
        assertThat(asaRequestWebhookEvent.networkRiskScore()).contains(0L)
        assertThat(asaRequestWebhookEvent.networkSpecificData())
            .contains(
                AsaRequestWebhookEvent.AsaNetworkSpecificData.builder()
                    .mastercard(
                        AsaRequestWebhookEvent.AsaNetworkSpecificData
                            .AsaNetworkSpecificDataMastercard
                            .builder()
                            .ecommerceSecurityLevelIndicator("xxx")
                            .addOnBehalfServiceResult(
                                AsaRequestWebhookEvent.AsaNetworkSpecificData
                                    .AsaNetworkSpecificDataMastercard
                                    .OnBehalfServiceResult
                                    .builder()
                                    .result1("x")
                                    .result2("x")
                                    .service("xx")
                                    .build()
                            )
                            .transactionTypeIdentifier("xxx")
                            .build()
                    )
                    .visa(
                        AsaRequestWebhookEvent.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                            .builder()
                            .businessApplicationIdentifier("xx")
                            .build()
                    )
                    .build()
            )
        assertThat(asaRequestWebhookEvent.pos())
            .contains(
                AsaRequestWebhookEvent.Pos.builder()
                    .entryMode(
                        AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.builder()
                            .card(AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Card.PRESENT)
                            .cardholder(
                                AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Cardholder
                                    .DEFERRED_BILLING
                            )
                            .pan(AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY)
                            .pinEntered(true)
                            .build()
                    )
                    .terminal(
                        AsaRequestWebhookEvent.Pos.AsaPosTerminal.builder()
                            .attended(true)
                            .cardRetentionCapable(true)
                            .onPremise(true)
                            .operator(
                                AsaRequestWebhookEvent.Pos.AsaPosTerminal.Operator.ADMINISTRATIVE
                            )
                            .partialApprovalCapable(true)
                            .pinCapability(
                                AsaRequestWebhookEvent.Pos.AsaPosTerminal.PinCapability.CAPABLE
                            )
                            .type(AsaRequestWebhookEvent.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                            .acceptorTerminalId(" r 0K9tW")
                            .build()
                    )
                    .build()
            )
        assertThat(asaRequestWebhookEvent.tokenInfo())
            .contains(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
        assertThat(asaRequestWebhookEvent.ttl())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val asaRequestWebhookEvent =
            AsaRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .authorizationAmount(0L)
                .avs(
                    AsaRequestWebhookEvent.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(AsaRequestWebhookEvent.Avs.AddressMatchResult.MATCH)
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    AsaRequestWebhookEvent.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .hostname("hostname")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            AsaRequestWebhookEvent.AsaRequestCard.SpendLimitDuration.ANNUALLY
                        )
                        .state(AsaRequestWebhookEvent.AsaRequestCard.State.CLOSED)
                        .type(AsaRequestWebhookEvent.AsaRequestCard.CardType.SINGLE_USE)
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    Merchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .settledAmount(0L)
                .status(AsaRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(AsaRequestWebhookEvent.TransactionInitiator.CARDHOLDER)
                .accountType(AsaRequestWebhookEvent.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    AsaRequestWebhookEvent.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            AsaRequestWebhookEvent.AsaRequestFleetInfo.FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    AsaRequestWebhookEvent.LatestChallenge.builder()
                        .phoneNumber("phone_number")
                        .status(AsaRequestWebhookEvent.LatestChallenge.Status.COMPLETED)
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .network(AsaRequestWebhookEvent.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    AsaRequestWebhookEvent.AsaNetworkSpecificData.builder()
                        .mastercard(
                            AsaRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    AsaRequestWebhookEvent.AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            AsaRequestWebhookEvent.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    AsaRequestWebhookEvent.Pos.builder()
                        .entryMode(
                            AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.builder()
                                .card(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Card.PRESENT
                                )
                                .cardholder(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(
                                    AsaRequestWebhookEvent.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY
                                )
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            AsaRequestWebhookEvent.Pos.AsaPosTerminal.builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    AsaRequestWebhookEvent.Pos.AsaPosTerminal.Operator
                                        .ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    AsaRequestWebhookEvent.Pos.AsaPosTerminal.PinCapability.CAPABLE
                                )
                                .type(AsaRequestWebhookEvent.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                                .acceptorTerminalId(" r 0K9tW")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedAsaRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(asaRequestWebhookEvent),
                jacksonTypeRef<AsaRequestWebhookEvent>(),
            )

        assertThat(roundtrippedAsaRequestWebhookEvent).isEqualTo(asaRequestWebhookEvent)
    }
}
