// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AuthRuleV2ListPageResponseTest {

    @Test
    fun create() {
        val authRuleV2ListPageResponse =
            AuthRuleV2ListPageResponse.builder()
                .addData(
                    AuthRule.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .currentVersion(
                            AuthRule.CurrentVersion.builder()
                                .parameters(
                                    VelocityLimitParams.builder()
                                        .period(
                                            VelocityLimitPeriod.TrailingWindowObject.builder()
                                                .duration(10L)
                                                .type(
                                                    VelocityLimitPeriod.TrailingWindowObject.Type
                                                        .CUSTOM
                                                )
                                                .build()
                                        )
                                        .scope(VelocityLimitParams.VelocityScope.CARD)
                                        .filters(
                                            VelocityLimitFilters.builder()
                                                .addExcludeCountry("USD")
                                                .addExcludeMcc("5542")
                                                .addIncludeCountry("USD")
                                                .addIncludeMcc("5542")
                                                .addIncludePanEntryMode(
                                                    VelocityLimitFilters.IncludePanEntryMode
                                                        .AUTO_ENTRY
                                                )
                                                .build()
                                        )
                                        .limitAmount(10000L)
                                        .limitCashAmount(5000L)
                                        .limitCashCount(0L)
                                        .limitCount(0L)
                                        .build()
                                )
                                .version(0L)
                                .build()
                        )
                        .draftVersion(
                            AuthRule.DraftVersion.builder()
                                .error("error")
                                .parameters(
                                    VelocityLimitParams.builder()
                                        .period(
                                            VelocityLimitPeriod.TrailingWindowObject.builder()
                                                .duration(10L)
                                                .type(
                                                    VelocityLimitPeriod.TrailingWindowObject.Type
                                                        .CUSTOM
                                                )
                                                .build()
                                        )
                                        .scope(VelocityLimitParams.VelocityScope.CARD)
                                        .filters(
                                            VelocityLimitFilters.builder()
                                                .addExcludeCountry("USD")
                                                .addExcludeMcc("5542")
                                                .addIncludeCountry("USD")
                                                .addIncludeMcc("5542")
                                                .addIncludePanEntryMode(
                                                    VelocityLimitFilters.IncludePanEntryMode
                                                        .AUTO_ENTRY
                                                )
                                                .build()
                                        )
                                        .limitAmount(10000L)
                                        .limitCashAmount(5000L)
                                        .limitCashCount(0L)
                                        .limitCount(0L)
                                        .build()
                                )
                                .state(AuthRule.DraftVersion.State.PENDING)
                                .version(0L)
                                .build()
                        )
                        .eventStream(EventStream.AUTHORIZATION)
                        .lithicManaged(true)
                        .name("name")
                        .programLevel(true)
                        .state(AuthRule.AuthRuleState.ACTIVE)
                        .type(AuthRule.AuthRuleType.VELOCITY_LIMIT)
                        .addExcludedAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addExcludedBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addExcludedCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .hasMore(true)
                .build()

        assertThat(authRuleV2ListPageResponse.data())
            .containsExactly(
                AuthRule.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .currentVersion(
                        AuthRule.CurrentVersion.builder()
                            .parameters(
                                VelocityLimitParams.builder()
                                    .period(
                                        VelocityLimitPeriod.TrailingWindowObject.builder()
                                            .duration(10L)
                                            .type(
                                                VelocityLimitPeriod.TrailingWindowObject.Type.CUSTOM
                                            )
                                            .build()
                                    )
                                    .scope(VelocityLimitParams.VelocityScope.CARD)
                                    .filters(
                                        VelocityLimitFilters.builder()
                                            .addExcludeCountry("USD")
                                            .addExcludeMcc("5542")
                                            .addIncludeCountry("USD")
                                            .addIncludeMcc("5542")
                                            .addIncludePanEntryMode(
                                                VelocityLimitFilters.IncludePanEntryMode.AUTO_ENTRY
                                            )
                                            .build()
                                    )
                                    .limitAmount(10000L)
                                    .limitCashAmount(5000L)
                                    .limitCashCount(0L)
                                    .limitCount(0L)
                                    .build()
                            )
                            .version(0L)
                            .build()
                    )
                    .draftVersion(
                        AuthRule.DraftVersion.builder()
                            .error("error")
                            .parameters(
                                VelocityLimitParams.builder()
                                    .period(
                                        VelocityLimitPeriod.TrailingWindowObject.builder()
                                            .duration(10L)
                                            .type(
                                                VelocityLimitPeriod.TrailingWindowObject.Type.CUSTOM
                                            )
                                            .build()
                                    )
                                    .scope(VelocityLimitParams.VelocityScope.CARD)
                                    .filters(
                                        VelocityLimitFilters.builder()
                                            .addExcludeCountry("USD")
                                            .addExcludeMcc("5542")
                                            .addIncludeCountry("USD")
                                            .addIncludeMcc("5542")
                                            .addIncludePanEntryMode(
                                                VelocityLimitFilters.IncludePanEntryMode.AUTO_ENTRY
                                            )
                                            .build()
                                    )
                                    .limitAmount(10000L)
                                    .limitCashAmount(5000L)
                                    .limitCashCount(0L)
                                    .limitCount(0L)
                                    .build()
                            )
                            .state(AuthRule.DraftVersion.State.PENDING)
                            .version(0L)
                            .build()
                    )
                    .eventStream(EventStream.AUTHORIZATION)
                    .lithicManaged(true)
                    .name("name")
                    .programLevel(true)
                    .state(AuthRule.AuthRuleState.ACTIVE)
                    .type(AuthRule.AuthRuleType.VELOCITY_LIMIT)
                    .addExcludedAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addExcludedBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addExcludedCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(authRuleV2ListPageResponse.hasMore()).isEqualTo(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val authRuleV2ListPageResponse =
            AuthRuleV2ListPageResponse.builder()
                .addData(
                    AuthRule.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .currentVersion(
                            AuthRule.CurrentVersion.builder()
                                .parameters(
                                    VelocityLimitParams.builder()
                                        .period(
                                            VelocityLimitPeriod.TrailingWindowObject.builder()
                                                .duration(10L)
                                                .type(
                                                    VelocityLimitPeriod.TrailingWindowObject.Type
                                                        .CUSTOM
                                                )
                                                .build()
                                        )
                                        .scope(VelocityLimitParams.VelocityScope.CARD)
                                        .filters(
                                            VelocityLimitFilters.builder()
                                                .addExcludeCountry("USD")
                                                .addExcludeMcc("5542")
                                                .addIncludeCountry("USD")
                                                .addIncludeMcc("5542")
                                                .addIncludePanEntryMode(
                                                    VelocityLimitFilters.IncludePanEntryMode
                                                        .AUTO_ENTRY
                                                )
                                                .build()
                                        )
                                        .limitAmount(10000L)
                                        .limitCashAmount(5000L)
                                        .limitCashCount(0L)
                                        .limitCount(0L)
                                        .build()
                                )
                                .version(0L)
                                .build()
                        )
                        .draftVersion(
                            AuthRule.DraftVersion.builder()
                                .error("error")
                                .parameters(
                                    VelocityLimitParams.builder()
                                        .period(
                                            VelocityLimitPeriod.TrailingWindowObject.builder()
                                                .duration(10L)
                                                .type(
                                                    VelocityLimitPeriod.TrailingWindowObject.Type
                                                        .CUSTOM
                                                )
                                                .build()
                                        )
                                        .scope(VelocityLimitParams.VelocityScope.CARD)
                                        .filters(
                                            VelocityLimitFilters.builder()
                                                .addExcludeCountry("USD")
                                                .addExcludeMcc("5542")
                                                .addIncludeCountry("USD")
                                                .addIncludeMcc("5542")
                                                .addIncludePanEntryMode(
                                                    VelocityLimitFilters.IncludePanEntryMode
                                                        .AUTO_ENTRY
                                                )
                                                .build()
                                        )
                                        .limitAmount(10000L)
                                        .limitCashAmount(5000L)
                                        .limitCashCount(0L)
                                        .limitCount(0L)
                                        .build()
                                )
                                .state(AuthRule.DraftVersion.State.PENDING)
                                .version(0L)
                                .build()
                        )
                        .eventStream(EventStream.AUTHORIZATION)
                        .lithicManaged(true)
                        .name("name")
                        .programLevel(true)
                        .state(AuthRule.AuthRuleState.ACTIVE)
                        .type(AuthRule.AuthRuleType.VELOCITY_LIMIT)
                        .addExcludedAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addExcludedBusinessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addExcludedCardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .hasMore(true)
                .build()

        val roundtrippedAuthRuleV2ListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(authRuleV2ListPageResponse),
                jacksonTypeRef<AuthRuleV2ListPageResponse>(),
            )

        assertThat(roundtrippedAuthRuleV2ListPageResponse).isEqualTo(authRuleV2ListPageResponse)
    }
}
