// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class AuthRuleMigrateV1ToV2ResponseTest {

    @Test
    fun createAuthRuleMigrateV1ToV2Response() {
        val authRuleMigrateV1ToV2Response =
            AuthRuleMigrateV1ToV2Response.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .cardTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .currentVersion(
                    AuthRuleMigrateV1ToV2Response.CurrentVersion.builder()
                        .parameters(
                            AuthRuleMigrateV1ToV2Response.CurrentVersion.AuthRuleParameters
                                .ofConditionalBlockParameters(
                                    AuthRuleMigrateV1ToV2Response.CurrentVersion.AuthRuleParameters
                                        .ConditionalBlockParameters
                                        .builder()
                                        .conditions(
                                            listOf(
                                                AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                    .AuthRuleParameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .builder()
                                                    .attribute(
                                                        AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Attribute
                                                            .MCC
                                                    )
                                                    .operation(
                                                        AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Operation
                                                            .IS_ONE_OF
                                                    )
                                                    .value(
                                                        AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Value
                                                            .ofString("string")
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                        )
                        .version(123L)
                        .build()
                )
                .draftVersion(
                    AuthRuleMigrateV1ToV2Response.DraftVersion.builder()
                        .parameters(
                            AuthRuleMigrateV1ToV2Response.DraftVersion.AuthRuleParameters
                                .ofConditionalBlockParameters(
                                    AuthRuleMigrateV1ToV2Response.DraftVersion.AuthRuleParameters
                                        .ConditionalBlockParameters
                                        .builder()
                                        .conditions(
                                            listOf(
                                                AuthRuleMigrateV1ToV2Response.DraftVersion
                                                    .AuthRuleParameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .builder()
                                                    .attribute(
                                                        AuthRuleMigrateV1ToV2Response.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Attribute
                                                            .MCC
                                                    )
                                                    .operation(
                                                        AuthRuleMigrateV1ToV2Response.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Operation
                                                            .IS_ONE_OF
                                                    )
                                                    .value(
                                                        AuthRuleMigrateV1ToV2Response.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Value
                                                            .ofString("string")
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                        )
                        .version(123L)
                        .build()
                )
                .programLevel(true)
                .state(AuthRuleMigrateV1ToV2Response.AuthRuleState.ACTIVE)
                .type(AuthRuleMigrateV1ToV2Response.AuthRuleType.CONDITIONAL_BLOCK)
                .build()
        assertThat(authRuleMigrateV1ToV2Response).isNotNull
        assertThat(authRuleMigrateV1ToV2Response.token())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(authRuleMigrateV1ToV2Response.accountTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(authRuleMigrateV1ToV2Response.cardTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(authRuleMigrateV1ToV2Response.currentVersion())
            .contains(
                AuthRuleMigrateV1ToV2Response.CurrentVersion.builder()
                    .parameters(
                        AuthRuleMigrateV1ToV2Response.CurrentVersion.AuthRuleParameters
                            .ofConditionalBlockParameters(
                                AuthRuleMigrateV1ToV2Response.CurrentVersion.AuthRuleParameters
                                    .ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                .AuthRuleParameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    AuthRuleMigrateV1ToV2Response.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(authRuleMigrateV1ToV2Response.draftVersion())
            .contains(
                AuthRuleMigrateV1ToV2Response.DraftVersion.builder()
                    .parameters(
                        AuthRuleMigrateV1ToV2Response.DraftVersion.AuthRuleParameters
                            .ofConditionalBlockParameters(
                                AuthRuleMigrateV1ToV2Response.DraftVersion.AuthRuleParameters
                                    .ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            AuthRuleMigrateV1ToV2Response.DraftVersion
                                                .AuthRuleParameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    AuthRuleMigrateV1ToV2Response.DraftVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    AuthRuleMigrateV1ToV2Response.DraftVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    AuthRuleMigrateV1ToV2Response.DraftVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(authRuleMigrateV1ToV2Response.programLevel()).isEqualTo(true)
        assertThat(authRuleMigrateV1ToV2Response.state())
            .isEqualTo(AuthRuleMigrateV1ToV2Response.AuthRuleState.ACTIVE)
        assertThat(authRuleMigrateV1ToV2Response.type())
            .isEqualTo(AuthRuleMigrateV1ToV2Response.AuthRuleType.CONDITIONAL_BLOCK)
    }
}
