// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CardAuthorizationApprovalRequestWebhookEventTest {

    @Test
    fun create() {
        val cardAuthorizationApprovalRequestWebhookEvent =
            CardAuthorizationApprovalRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .amounts(
                    CardAuthorizationApprovalRequestWebhookEvent.Amounts.builder()
                        .cardholder(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.ConvertedAmount
                                .builder()
                                .amount(0L)
                                .conversionRate("1.000000")
                                .currency("USD")
                                .build()
                        )
                        .hold(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .merchant(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .settlement(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .build()
                )
                .authorizationAmount(0L)
                .avs(
                    CardAuthorizationApprovalRequestWebhookEvent.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(
                            CardAuthorizationApprovalRequestWebhookEvent.Avs.AddressMatchResult
                                .MATCH
                        )
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .hostname("hostname")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard
                                .SpendLimitDuration
                                .ANNUALLY
                        )
                        .state(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.State.CLOSED
                        )
                        .type(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.CardType
                                .SINGLE_USE
                        )
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .eventType(
                    CardAuthorizationApprovalRequestWebhookEvent.EventType
                        .CARD_AUTHORIZATION_APPROVAL_REQUEST
                )
                .merchant(
                    Merchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .settledAmount(0L)
                .status(CardAuthorizationApprovalRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(
                    CardAuthorizationApprovalRequestWebhookEvent.TransactionInitiator.CARDHOLDER
                )
                .accountType(CardAuthorizationApprovalRequestWebhookEvent.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                                .FleetPromptCode
                                .NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                                .FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.builder()
                        .phoneNumber("phone_number")
                        .status(
                            CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.Status
                                .COMPLETED
                        )
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .network(CardAuthorizationApprovalRequestWebhookEvent.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData.builder()
                        .mastercard(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    CardAuthorizationApprovalRequestWebhookEvent
                                        .AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    CardAuthorizationApprovalRequestWebhookEvent.Pos.builder()
                        .entryMode(
                            CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaRequestPosEntryMode
                                .builder()
                                .card(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Card
                                        .PRESENT
                                )
                                .cardholder(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Pan
                                        .AUTO_ENTRY
                                )
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                .builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .Operator
                                        .ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .PinCapability
                                        .CAPABLE
                                )
                                .type(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .Type
                                        .ADMINISTRATIVE
                                )
                                .acceptorTerminalId(" r 0K9tW")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(cardAuthorizationApprovalRequestWebhookEvent.token())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.acquirerFee()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.amount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.amounts())
            .isEqualTo(
                CardAuthorizationApprovalRequestWebhookEvent.Amounts.builder()
                    .cardholder(
                        CardAuthorizationApprovalRequestWebhookEvent.Amounts.ConvertedAmount
                            .builder()
                            .amount(0L)
                            .conversionRate("1.000000")
                            .currency("USD")
                            .build()
                    )
                    .hold(
                        CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .merchant(
                        CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .settlement(
                        CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.authorizationAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.avs())
            .isEqualTo(
                CardAuthorizationApprovalRequestWebhookEvent.Avs.builder()
                    .address("address")
                    .addressOnFileMatch(
                        CardAuthorizationApprovalRequestWebhookEvent.Avs.AddressMatchResult.MATCH
                    )
                    .zipcode("zipcode")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.card())
            .isEqualTo(
                CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .hostname("hostname")
                    .lastFour("last_four")
                    .memo("memo")
                    .spendLimit(0L)
                    .spendLimitDuration(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard
                            .SpendLimitDuration
                            .ANNUALLY
                    )
                    .state(CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.State.CLOSED)
                    .type(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.CardType
                            .SINGLE_USE
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cardholderCurrency())
            .isEqualTo("cardholder_currency")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cashAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.eventType())
            .isEqualTo(
                CardAuthorizationApprovalRequestWebhookEvent.EventType
                    .CARD_AUTHORIZATION_APPROVAL_REQUEST
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchant())
            .isEqualTo(
                Merchant.builder()
                    .acceptorId("333301802529120")
                    .acquiringInstitutionId("191231")
                    .city("NEW YORK")
                    .country("USA")
                    .descriptor("COFFEE SHOP")
                    .mcc("5812")
                    .state("NY")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchantAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchantCurrency()).isEqualTo("USD")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.settledAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.status())
            .isEqualTo(CardAuthorizationApprovalRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.transactionInitiator())
            .isEqualTo(CardAuthorizationApprovalRequestWebhookEvent.TransactionInitiator.CARDHOLDER)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.accountType())
            .contains(CardAuthorizationApprovalRequestWebhookEvent.AccountType.CHECKING)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cardholderAuthentication())
            .contains(
                CardholderAuthentication.builder()
                    .authenticationMethod(
                        CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                    )
                    .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                    .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                    .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                    .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cashback()).contains(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.conversionRate()).contains(0.0)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.eventToken())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.fleetInfo())
            .contains(
                CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo.builder()
                    .fleetPromptCode(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                            .FleetPromptCode
                            .NO_PROMPT
                    )
                    .fleetRestrictionCode(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                            .FleetRestrictionCode
                            .NO_RESTRICTIONS
                    )
                    .driverNumber("driver_number")
                    .vehicleNumber("vehicle_number")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.latestChallenge())
            .contains(
                CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.builder()
                    .phoneNumber("phone_number")
                    .status(
                        CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.Status
                            .COMPLETED
                    )
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.network())
            .contains(CardAuthorizationApprovalRequestWebhookEvent.Network.AMEX)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.networkRiskScore()).contains(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.networkSpecificData())
            .contains(
                CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData.builder()
                    .mastercard(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                            .AsaNetworkSpecificDataMastercard
                            .builder()
                            .ecommerceSecurityLevelIndicator("xxx")
                            .addOnBehalfServiceResult(
                                CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                                    .AsaNetworkSpecificDataMastercard
                                    .OnBehalfServiceResult
                                    .builder()
                                    .result1("x")
                                    .result2("x")
                                    .service("xx")
                                    .build()
                            )
                            .transactionTypeIdentifier("xxx")
                            .build()
                    )
                    .visa(
                        CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                            .AsaNetworkSpecificDataVisa
                            .builder()
                            .businessApplicationIdentifier("xx")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.pos())
            .contains(
                CardAuthorizationApprovalRequestWebhookEvent.Pos.builder()
                    .entryMode(
                        CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaRequestPosEntryMode
                            .builder()
                            .card(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos
                                    .AsaRequestPosEntryMode
                                    .Card
                                    .PRESENT
                            )
                            .cardholder(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos
                                    .AsaRequestPosEntryMode
                                    .Cardholder
                                    .DEFERRED_BILLING
                            )
                            .pan(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos
                                    .AsaRequestPosEntryMode
                                    .Pan
                                    .AUTO_ENTRY
                            )
                            .pinEntered(true)
                            .build()
                    )
                    .terminal(
                        CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal.builder()
                            .attended(true)
                            .cardRetentionCapable(true)
                            .onPremise(true)
                            .operator(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                    .Operator
                                    .ADMINISTRATIVE
                            )
                            .partialApprovalCapable(true)
                            .pinCapability(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                    .PinCapability
                                    .CAPABLE
                            )
                            .type(
                                CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal.Type
                                    .ADMINISTRATIVE
                            )
                            .acceptorTerminalId(" r 0K9tW")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.tokenInfo())
            .contains(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.ttl())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val cardAuthorizationApprovalRequestWebhookEvent =
            CardAuthorizationApprovalRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .amounts(
                    CardAuthorizationApprovalRequestWebhookEvent.Amounts.builder()
                        .cardholder(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.ConvertedAmount
                                .builder()
                                .amount(0L)
                                .conversionRate("1.000000")
                                .currency("USD")
                                .build()
                        )
                        .hold(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .merchant(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .settlement(
                            CardAuthorizationApprovalRequestWebhookEvent.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .build()
                )
                .authorizationAmount(0L)
                .avs(
                    CardAuthorizationApprovalRequestWebhookEvent.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(
                            CardAuthorizationApprovalRequestWebhookEvent.Avs.AddressMatchResult
                                .MATCH
                        )
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .hostname("hostname")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard
                                .SpendLimitDuration
                                .ANNUALLY
                        )
                        .state(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.State.CLOSED
                        )
                        .type(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestCard.CardType
                                .SINGLE_USE
                        )
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .eventType(
                    CardAuthorizationApprovalRequestWebhookEvent.EventType
                        .CARD_AUTHORIZATION_APPROVAL_REQUEST
                )
                .merchant(
                    Merchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .settledAmount(0L)
                .status(CardAuthorizationApprovalRequestWebhookEvent.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(
                    CardAuthorizationApprovalRequestWebhookEvent.TransactionInitiator.CARDHOLDER
                )
                .accountType(CardAuthorizationApprovalRequestWebhookEvent.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                                .FleetPromptCode
                                .NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaRequestFleetInfo
                                .FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.builder()
                        .phoneNumber("phone_number")
                        .status(
                            CardAuthorizationApprovalRequestWebhookEvent.LatestChallenge.Status
                                .COMPLETED
                        )
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .network(CardAuthorizationApprovalRequestWebhookEvent.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData.builder()
                        .mastercard(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    CardAuthorizationApprovalRequestWebhookEvent
                                        .AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            CardAuthorizationApprovalRequestWebhookEvent.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    CardAuthorizationApprovalRequestWebhookEvent.Pos.builder()
                        .entryMode(
                            CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaRequestPosEntryMode
                                .builder()
                                .card(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Card
                                        .PRESENT
                                )
                                .cardholder(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos
                                        .AsaRequestPosEntryMode
                                        .Pan
                                        .AUTO_ENTRY
                                )
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                .builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .Operator
                                        .ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .PinCapability
                                        .CAPABLE
                                )
                                .type(
                                    CardAuthorizationApprovalRequestWebhookEvent.Pos.AsaPosTerminal
                                        .Type
                                        .ADMINISTRATIVE
                                )
                                .acceptorTerminalId(" r 0K9tW")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedCardAuthorizationApprovalRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(cardAuthorizationApprovalRequestWebhookEvent),
                jacksonTypeRef<CardAuthorizationApprovalRequestWebhookEvent>(),
            )

        assertThat(roundtrippedCardAuthorizationApprovalRequestWebhookEvent)
            .isEqualTo(cardAuthorizationApprovalRequestWebhookEvent)
    }
}
