// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CardAuthorizationApprovalRequestWebhookEventTest {

    @Test
    fun create() {
        val cardAuthorizationApprovalRequestWebhookEvent =
            CardAuthorizationApprovalRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .amounts(
                    CardAuthorization.Amounts.builder()
                        .cardholder(
                            CardAuthorization.Amounts.ConvertedAmount.builder()
                                .amount(0L)
                                .conversionRate("1.000000")
                                .currency("USD")
                                .build()
                        )
                        .hold(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .merchant(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .settlement(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .build()
                )
                .authorizationAmount(0L)
                .avs(
                    CardAuthorization.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(CardAuthorization.Avs.AddressMatchResult.MATCH)
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    CardAuthorization.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            CardAuthorization.AsaRequestCard.SpendLimitDuration.ANNUALLY
                        )
                        .state(CardAuthorization.AsaRequestCard.State.CLOSED)
                        .type(CardAuthorization.AsaRequestCard.CardType.SINGLE_USE)
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    CardAuthorization.TransactionMerchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .phoneNumber("5551234567")
                        .postalCode("10001")
                        .streetAddress("123 MAIN ST")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .nameValidation(
                    CardAuthorization.NameValidation.builder()
                        .name(
                            CardAuthorization.NameValidation.Name.builder()
                                .first("first")
                                .last("last")
                                .middle("middle")
                                .build()
                        )
                        .nameOnFileMatch(
                            CardAuthorization.NameValidation.NameValidationResult.builder()
                                .fullName(
                                    CardAuthorization.NameValidation.NameValidationResult.FullName
                                        .MATCH
                                )
                                .build()
                        )
                        .build()
                )
                .serviceLocation(
                    CardAuthorization.ServiceLocation.builder()
                        .city("city")
                        .country("country")
                        .postalCode("postal_code")
                        .state("state")
                        .streetAddress("street_address")
                        .build()
                )
                .settledAmount(0L)
                .status(CardAuthorization.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(CardAuthorization.TransactionInitiator.CARDHOLDER)
                .accountType(CardAuthorization.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    CardAuthorization.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            CardAuthorization.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            CardAuthorization.AsaRequestFleetInfo.FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    CardAuthorization.LatestChallenge.builder()
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .method(CardAuthorization.LatestChallenge.Method.SMS)
                        .phoneNumber("phone_number")
                        .status(CardAuthorization.LatestChallenge.Status.COMPLETED)
                        .build()
                )
                .network(CardAuthorization.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    CardAuthorization.AsaNetworkSpecificData.builder()
                        .mastercard(
                            CardAuthorization.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    CardAuthorization.AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            CardAuthorization.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    CardAuthorization.Pos.builder()
                        .entryMode(
                            CardAuthorization.Pos.AsaRequestPosEntryMode.builder()
                                .card(CardAuthorization.Pos.AsaRequestPosEntryMode.Card.PRESENT)
                                .cardholder(
                                    CardAuthorization.Pos.AsaRequestPosEntryMode.Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(CardAuthorization.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY)
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            CardAuthorization.Pos.AsaPosTerminal.builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    CardAuthorization.Pos.AsaPosTerminal.Operator.ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    CardAuthorization.Pos.AsaPosTerminal.PinCapability.CAPABLE
                                )
                                .type(CardAuthorization.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                                .acceptorTerminalId("5([<,yN%")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .eventType(
                    CardAuthorizationApprovalRequestWebhookEvent.EventType
                        .CARD_AUTHORIZATION_APPROVAL_REQUEST
                )
                .build()

        assertThat(cardAuthorizationApprovalRequestWebhookEvent.token())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.acquirerFee()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.amount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.amounts())
            .isEqualTo(
                CardAuthorization.Amounts.builder()
                    .cardholder(
                        CardAuthorization.Amounts.ConvertedAmount.builder()
                            .amount(0L)
                            .conversionRate("1.000000")
                            .currency("USD")
                            .build()
                    )
                    .hold(
                        CardAuthorization.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .merchant(
                        CardAuthorization.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .settlement(
                        CardAuthorization.Amounts.Amount.builder()
                            .amount(0L)
                            .currency("USD")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.authorizationAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.avs())
            .isEqualTo(
                CardAuthorization.Avs.builder()
                    .address("address")
                    .addressOnFileMatch(CardAuthorization.Avs.AddressMatchResult.MATCH)
                    .zipcode("zipcode")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.card())
            .isEqualTo(
                CardAuthorization.AsaRequestCard.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .lastFour("last_four")
                    .memo("memo")
                    .spendLimit(0L)
                    .spendLimitDuration(
                        CardAuthorization.AsaRequestCard.SpendLimitDuration.ANNUALLY
                    )
                    .state(CardAuthorization.AsaRequestCard.State.CLOSED)
                    .type(CardAuthorization.AsaRequestCard.CardType.SINGLE_USE)
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cardholderCurrency())
            .isEqualTo("cardholder_currency")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cashAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchant())
            .isEqualTo(
                CardAuthorization.TransactionMerchant.builder()
                    .acceptorId("333301802529120")
                    .acquiringInstitutionId("191231")
                    .city("NEW YORK")
                    .country("USA")
                    .descriptor("COFFEE SHOP")
                    .mcc("5812")
                    .state("NY")
                    .phoneNumber("5551234567")
                    .postalCode("10001")
                    .streetAddress("123 MAIN ST")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchantAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.merchantCurrency()).isEqualTo("USD")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.nameValidation())
            .contains(
                CardAuthorization.NameValidation.builder()
                    .name(
                        CardAuthorization.NameValidation.Name.builder()
                            .first("first")
                            .last("last")
                            .middle("middle")
                            .build()
                    )
                    .nameOnFileMatch(
                        CardAuthorization.NameValidation.NameValidationResult.builder()
                            .fullName(
                                CardAuthorization.NameValidation.NameValidationResult.FullName.MATCH
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.serviceLocation())
            .contains(
                CardAuthorization.ServiceLocation.builder()
                    .city("city")
                    .country("country")
                    .postalCode("postal_code")
                    .state("state")
                    .streetAddress("street_address")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.settledAmount()).isEqualTo(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.status())
            .isEqualTo(CardAuthorization.AsaRequestStatus.AUTHORIZATION)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.transactionInitiator())
            .isEqualTo(CardAuthorization.TransactionInitiator.CARDHOLDER)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.accountType())
            .contains(CardAuthorization.AccountType.CHECKING)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cardholderAuthentication())
            .contains(
                CardholderAuthentication.builder()
                    .authenticationMethod(
                        CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                    )
                    .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                    .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                    .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                    .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.cashback()).contains(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.conversionRate()).contains(0.0)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.eventToken())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.fleetInfo())
            .contains(
                CardAuthorization.AsaRequestFleetInfo.builder()
                    .fleetPromptCode(
                        CardAuthorization.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                    )
                    .fleetRestrictionCode(
                        CardAuthorization.AsaRequestFleetInfo.FleetRestrictionCode.NO_RESTRICTIONS
                    )
                    .driverNumber("driver_number")
                    .vehicleNumber("vehicle_number")
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.latestChallenge())
            .contains(
                CardAuthorization.LatestChallenge.builder()
                    .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .method(CardAuthorization.LatestChallenge.Method.SMS)
                    .phoneNumber("phone_number")
                    .status(CardAuthorization.LatestChallenge.Status.COMPLETED)
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.network())
            .contains(CardAuthorization.Network.AMEX)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.networkRiskScore()).contains(0L)
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.networkSpecificData())
            .contains(
                CardAuthorization.AsaNetworkSpecificData.builder()
                    .mastercard(
                        CardAuthorization.AsaNetworkSpecificData.AsaNetworkSpecificDataMastercard
                            .builder()
                            .ecommerceSecurityLevelIndicator("xxx")
                            .addOnBehalfServiceResult(
                                CardAuthorization.AsaNetworkSpecificData
                                    .AsaNetworkSpecificDataMastercard
                                    .OnBehalfServiceResult
                                    .builder()
                                    .result1("x")
                                    .result2("x")
                                    .service("xx")
                                    .build()
                            )
                            .transactionTypeIdentifier("xxx")
                            .build()
                    )
                    .visa(
                        CardAuthorization.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                            .builder()
                            .businessApplicationIdentifier("xx")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.pos())
            .contains(
                CardAuthorization.Pos.builder()
                    .entryMode(
                        CardAuthorization.Pos.AsaRequestPosEntryMode.builder()
                            .card(CardAuthorization.Pos.AsaRequestPosEntryMode.Card.PRESENT)
                            .cardholder(
                                CardAuthorization.Pos.AsaRequestPosEntryMode.Cardholder
                                    .DEFERRED_BILLING
                            )
                            .pan(CardAuthorization.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY)
                            .pinEntered(true)
                            .build()
                    )
                    .terminal(
                        CardAuthorization.Pos.AsaPosTerminal.builder()
                            .attended(true)
                            .cardRetentionCapable(true)
                            .onPremise(true)
                            .operator(CardAuthorization.Pos.AsaPosTerminal.Operator.ADMINISTRATIVE)
                            .partialApprovalCapable(true)
                            .pinCapability(
                                CardAuthorization.Pos.AsaPosTerminal.PinCapability.CAPABLE
                            )
                            .type(CardAuthorization.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                            .acceptorTerminalId("5([<,yN%")
                            .build()
                    )
                    .build()
            )
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.tokenInfo())
            .contains(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.ttl())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(cardAuthorizationApprovalRequestWebhookEvent.eventType())
            .isEqualTo(
                CardAuthorizationApprovalRequestWebhookEvent.EventType
                    .CARD_AUTHORIZATION_APPROVAL_REQUEST
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val cardAuthorizationApprovalRequestWebhookEvent =
            CardAuthorizationApprovalRequestWebhookEvent.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .acquirerFee(0L)
                .amount(0L)
                .amounts(
                    CardAuthorization.Amounts.builder()
                        .cardholder(
                            CardAuthorization.Amounts.ConvertedAmount.builder()
                                .amount(0L)
                                .conversionRate("1.000000")
                                .currency("USD")
                                .build()
                        )
                        .hold(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .merchant(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .settlement(
                            CardAuthorization.Amounts.Amount.builder()
                                .amount(0L)
                                .currency("USD")
                                .build()
                        )
                        .build()
                )
                .authorizationAmount(0L)
                .avs(
                    CardAuthorization.Avs.builder()
                        .address("address")
                        .addressOnFileMatch(CardAuthorization.Avs.AddressMatchResult.MATCH)
                        .zipcode("zipcode")
                        .build()
                )
                .card(
                    CardAuthorization.AsaRequestCard.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .lastFour("last_four")
                        .memo("memo")
                        .spendLimit(0L)
                        .spendLimitDuration(
                            CardAuthorization.AsaRequestCard.SpendLimitDuration.ANNUALLY
                        )
                        .state(CardAuthorization.AsaRequestCard.State.CLOSED)
                        .type(CardAuthorization.AsaRequestCard.CardType.SINGLE_USE)
                        .build()
                )
                .cardholderCurrency("cardholder_currency")
                .cashAmount(0L)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    CardAuthorization.TransactionMerchant.builder()
                        .acceptorId("333301802529120")
                        .acquiringInstitutionId("191231")
                        .city("NEW YORK")
                        .country("USA")
                        .descriptor("COFFEE SHOP")
                        .mcc("5812")
                        .state("NY")
                        .phoneNumber("5551234567")
                        .postalCode("10001")
                        .streetAddress("123 MAIN ST")
                        .build()
                )
                .merchantAmount(0L)
                .merchantCurrency("USD")
                .nameValidation(
                    CardAuthorization.NameValidation.builder()
                        .name(
                            CardAuthorization.NameValidation.Name.builder()
                                .first("first")
                                .last("last")
                                .middle("middle")
                                .build()
                        )
                        .nameOnFileMatch(
                            CardAuthorization.NameValidation.NameValidationResult.builder()
                                .fullName(
                                    CardAuthorization.NameValidation.NameValidationResult.FullName
                                        .MATCH
                                )
                                .build()
                        )
                        .build()
                )
                .serviceLocation(
                    CardAuthorization.ServiceLocation.builder()
                        .city("city")
                        .country("country")
                        .postalCode("postal_code")
                        .state("state")
                        .streetAddress("street_address")
                        .build()
                )
                .settledAmount(0L)
                .status(CardAuthorization.AsaRequestStatus.AUTHORIZATION)
                .transactionInitiator(CardAuthorization.TransactionInitiator.CARDHOLDER)
                .accountType(CardAuthorization.AccountType.CHECKING)
                .cardholderAuthentication(
                    CardholderAuthentication.builder()
                        .authenticationMethod(
                            CardholderAuthentication.AuthenticationMethod.FRICTIONLESS
                        )
                        .authenticationResult(CardholderAuthentication.AuthenticationResult.SUCCESS)
                        .decisionMadeBy(CardholderAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .liabilityShift(CardholderAuthentication.LiabilityShift._3DS_AUTHENTICATED)
                        .threeDSAuthenticationToken("a6e372d0-b40a-43eb-b0d1-4e1aebef5875")
                        .build()
                )
                .cashback(0L)
                .conversionRate(0.0)
                .eventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .fleetInfo(
                    CardAuthorization.AsaRequestFleetInfo.builder()
                        .fleetPromptCode(
                            CardAuthorization.AsaRequestFleetInfo.FleetPromptCode.NO_PROMPT
                        )
                        .fleetRestrictionCode(
                            CardAuthorization.AsaRequestFleetInfo.FleetRestrictionCode
                                .NO_RESTRICTIONS
                        )
                        .driverNumber("driver_number")
                        .vehicleNumber("vehicle_number")
                        .build()
                )
                .latestChallenge(
                    CardAuthorization.LatestChallenge.builder()
                        .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .method(CardAuthorization.LatestChallenge.Method.SMS)
                        .phoneNumber("phone_number")
                        .status(CardAuthorization.LatestChallenge.Status.COMPLETED)
                        .build()
                )
                .network(CardAuthorization.Network.AMEX)
                .networkRiskScore(0L)
                .networkSpecificData(
                    CardAuthorization.AsaNetworkSpecificData.builder()
                        .mastercard(
                            CardAuthorization.AsaNetworkSpecificData
                                .AsaNetworkSpecificDataMastercard
                                .builder()
                                .ecommerceSecurityLevelIndicator("xxx")
                                .addOnBehalfServiceResult(
                                    CardAuthorization.AsaNetworkSpecificData
                                        .AsaNetworkSpecificDataMastercard
                                        .OnBehalfServiceResult
                                        .builder()
                                        .result1("x")
                                        .result2("x")
                                        .service("xx")
                                        .build()
                                )
                                .transactionTypeIdentifier("xxx")
                                .build()
                        )
                        .visa(
                            CardAuthorization.AsaNetworkSpecificData.AsaNetworkSpecificDataVisa
                                .builder()
                                .businessApplicationIdentifier("xx")
                                .build()
                        )
                        .build()
                )
                .pos(
                    CardAuthorization.Pos.builder()
                        .entryMode(
                            CardAuthorization.Pos.AsaRequestPosEntryMode.builder()
                                .card(CardAuthorization.Pos.AsaRequestPosEntryMode.Card.PRESENT)
                                .cardholder(
                                    CardAuthorization.Pos.AsaRequestPosEntryMode.Cardholder
                                        .DEFERRED_BILLING
                                )
                                .pan(CardAuthorization.Pos.AsaRequestPosEntryMode.Pan.AUTO_ENTRY)
                                .pinEntered(true)
                                .build()
                        )
                        .terminal(
                            CardAuthorization.Pos.AsaPosTerminal.builder()
                                .attended(true)
                                .cardRetentionCapable(true)
                                .onPremise(true)
                                .operator(
                                    CardAuthorization.Pos.AsaPosTerminal.Operator.ADMINISTRATIVE
                                )
                                .partialApprovalCapable(true)
                                .pinCapability(
                                    CardAuthorization.Pos.AsaPosTerminal.PinCapability.CAPABLE
                                )
                                .type(CardAuthorization.Pos.AsaPosTerminal.Type.ADMINISTRATIVE)
                                .acceptorTerminalId("5([<,yN%")
                                .build()
                        )
                        .build()
                )
                .tokenInfo(TokenInfo.builder().walletType(TokenInfo.WalletType.APPLE_PAY).build())
                .ttl(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .eventType(
                    CardAuthorizationApprovalRequestWebhookEvent.EventType
                        .CARD_AUTHORIZATION_APPROVAL_REQUEST
                )
                .build()

        val roundtrippedCardAuthorizationApprovalRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(cardAuthorizationApprovalRequestWebhookEvent),
                jacksonTypeRef<CardAuthorizationApprovalRequestWebhookEvent>(),
            )

        assertThat(roundtrippedCardAuthorizationApprovalRequestWebhookEvent)
            .isEqualTo(cardAuthorizationApprovalRequestWebhookEvent)
    }
}
