// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DigitalWalletTokenizationApprovalRequestWebhookEventTest {

    @Test
    fun create() {
        val digitalWalletTokenizationApprovalRequestWebhookEvent =
            DigitalWalletTokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2023-09-18T12:34:56Z"))
                .digitalWalletTokenMetadata(
                    TokenMetadata.builder()
                        .paymentAccountInfo(
                            TokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                        .phoneNumber("+15555555555")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_ref_1234567890123456789012345678")
                                .paymentAccountReference("ref_1234567890123456789012")
                                .tokenUniqueReference(
                                    "token_unique_ref_1234567890123456789012345678"
                                )
                                .build()
                        )
                        .status("Pending")
                        .paymentAppInstanceId("app_instance_123456789012345678901234567890")
                        .tokenRequestorId("12345678901")
                        .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .eventType(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                        .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED
                )
                .tokenizationChannel(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                        .DIGITAL_WALLET
                )
                .tokenizationToken("tok_1234567890abcdef")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("Reason1")
                        .build()
                )
                .customerTokenizationDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent
                        .CustomerTokenizationDecision
                        .builder()
                        .outcome(
                            DigitalWalletTokenizationApprovalRequestWebhookEvent
                                .CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("550e8400-e29b-41d4-a716-446655440003")
                        .explanation("Account risk too high")
                        .name("CustomerAccountRule")
                        .result(TokenizationRuleResult.Result.DECLINED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                        .PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.accountToken())
            .isEqualTo("00000000-0000-0000-0000-000000000002")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.cardToken())
            .isEqualTo("00000000-0000-0000-0000-000000000001")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2023-09-18T12:34:56Z"))
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent.digitalWalletTokenMetadata()
            )
            .isEqualTo(
                TokenMetadata.builder()
                    .paymentAccountInfo(
                        TokenMetadata.PaymentAccountInfo.builder()
                            .accountHolderData(
                                TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                    .phoneNumber("+15555555555")
                                    .build()
                            )
                            .panUniqueReference("pan_unique_ref_1234567890123456789012345678")
                            .paymentAccountReference("ref_1234567890123456789012")
                            .tokenUniqueReference("token_unique_ref_1234567890123456789012345678")
                            .build()
                    )
                    .status("Pending")
                    .paymentAppInstanceId("app_instance_123456789012345678901234567890")
                    .tokenRequestorId("12345678901")
                    .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.eventType())
            .isEqualTo(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                    .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.issuerDecision())
            .isEqualTo(DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED)
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationChannel())
            .isEqualTo(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                    .DIGITAL_WALLET
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationToken())
            .isEqualTo("tok_1234567890abcdef")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.walletDecisioningInfo())
            .isEqualTo(
                WalletDecisioningInfo.builder()
                    .accountScore("100")
                    .deviceScore("100")
                    .recommendedDecision("Decision1")
                    .addRecommendationReason("Reason1")
                    .build()
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent.customerTokenizationDecision()
            )
            .contains(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision
                    .builder()
                    .outcome(
                        DigitalWalletTokenizationApprovalRequestWebhookEvent
                            .CustomerTokenizationDecision
                            .Outcome
                            .APPROVED
                    )
                    .responderUrl("https://example.com")
                    .latency("100")
                    .responseCode("123456")
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.device())
            .contains(
                Device.builder()
                    .imei("123456789012345")
                    .ipAddress("1.1.1.1")
                    .location("37.3860517/-122.0838511")
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.ruleResults().getOrNull())
            .containsExactly(
                TokenizationRuleResult.builder()
                    .authRuleToken("550e8400-e29b-41d4-a716-446655440003")
                    .explanation("Account risk too high")
                    .name("CustomerAccountRule")
                    .result(TokenizationRuleResult.Result.DECLINED)
                    .build()
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent
                    .tokenizationDeclineReasons()
                    .getOrNull()
            )
            .containsExactly(TokenizationDeclineReason.ACCOUNT_SCORE_1)
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationSource())
            .contains(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                    .PUSH_PROVISION
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent
                    .tokenizationTfaReasons()
                    .getOrNull()
            )
            .containsExactly(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val digitalWalletTokenizationApprovalRequestWebhookEvent =
            DigitalWalletTokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2023-09-18T12:34:56Z"))
                .digitalWalletTokenMetadata(
                    TokenMetadata.builder()
                        .paymentAccountInfo(
                            TokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                        .phoneNumber("+15555555555")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_ref_1234567890123456789012345678")
                                .paymentAccountReference("ref_1234567890123456789012")
                                .tokenUniqueReference(
                                    "token_unique_ref_1234567890123456789012345678"
                                )
                                .build()
                        )
                        .status("Pending")
                        .paymentAppInstanceId("app_instance_123456789012345678901234567890")
                        .tokenRequestorId("12345678901")
                        .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .eventType(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                        .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED
                )
                .tokenizationChannel(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                        .DIGITAL_WALLET
                )
                .tokenizationToken("tok_1234567890abcdef")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("Reason1")
                        .build()
                )
                .customerTokenizationDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent
                        .CustomerTokenizationDecision
                        .builder()
                        .outcome(
                            DigitalWalletTokenizationApprovalRequestWebhookEvent
                                .CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("550e8400-e29b-41d4-a716-446655440003")
                        .explanation("Account risk too high")
                        .name("CustomerAccountRule")
                        .result(TokenizationRuleResult.Result.DECLINED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                        .PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        val roundtrippedDigitalWalletTokenizationApprovalRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(digitalWalletTokenizationApprovalRequestWebhookEvent),
                jacksonTypeRef<DigitalWalletTokenizationApprovalRequestWebhookEvent>(),
            )

        assertThat(roundtrippedDigitalWalletTokenizationApprovalRequestWebhookEvent)
            .isEqualTo(digitalWalletTokenizationApprovalRequestWebhookEvent)
    }
}
