// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DigitalWalletTokenizationApprovalRequestWebhookEventTest {

    @Test
    fun create() {
        val digitalWalletTokenizationApprovalRequestWebhookEvent =
            DigitalWalletTokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerTokenizationDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent
                        .CustomerTokenizationDecision
                        .builder()
                        .outcome(
                            DigitalWalletTokenizationApprovalRequestWebhookEvent
                                .CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .eventType(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                        .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED
                )
                .tokenizationChannel(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                        .DIGITAL_WALLET
                )
                .tokenizationToken("tokenization_token")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("string")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .digitalWalletTokenMetadata(
                    DigitalWalletTokenMetadata.builder()
                        .paymentAccountInfo(
                            DigitalWalletTokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    DigitalWalletTokenMetadata.PaymentAccountInfo.AccountHolderData
                                        .builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_reference")
                                .paymentAccountReference("payment_account_reference")
                                .tokenUniqueReference("token_unique_reference")
                                .build()
                        )
                        .status("status")
                        .paymentAppInstanceId("payment_app_instance_id")
                        .tokenRequestorId("xxxxxxxxxxx")
                        .tokenRequestorName(DigitalWalletTokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .explanation("explanation")
                        .name("name")
                        .result(TokenizationRuleResult.Result.APPROVED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                        .PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.accountToken())
            .isEqualTo("00000000-0000-0000-0000-000000000002")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.cardToken())
            .isEqualTo("00000000-0000-0000-0000-000000000001")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent.customerTokenizationDecision()
            )
            .contains(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision
                    .builder()
                    .outcome(
                        DigitalWalletTokenizationApprovalRequestWebhookEvent
                            .CustomerTokenizationDecision
                            .Outcome
                            .APPROVED
                    )
                    .responderUrl("https://example.com")
                    .latency("100")
                    .responseCode("123456")
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.eventType())
            .isEqualTo(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                    .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.issuerDecision())
            .isEqualTo(DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED)
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationChannel())
            .isEqualTo(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                    .DIGITAL_WALLET
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationToken())
            .isEqualTo("tokenization_token")
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.walletDecisioningInfo())
            .isEqualTo(
                WalletDecisioningInfo.builder()
                    .accountScore("100")
                    .deviceScore("100")
                    .recommendedDecision("Decision1")
                    .addRecommendationReason("string")
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.device())
            .contains(
                Device.builder()
                    .imei("123456789012345")
                    .ipAddress("1.1.1.1")
                    .location("37.3860517/-122.0838511")
                    .build()
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent.digitalWalletTokenMetadata()
            )
            .contains(
                DigitalWalletTokenMetadata.builder()
                    .paymentAccountInfo(
                        DigitalWalletTokenMetadata.PaymentAccountInfo.builder()
                            .accountHolderData(
                                DigitalWalletTokenMetadata.PaymentAccountInfo.AccountHolderData
                                    .builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .panUniqueReference("pan_unique_reference")
                            .paymentAccountReference("payment_account_reference")
                            .tokenUniqueReference("token_unique_reference")
                            .build()
                    )
                    .status("status")
                    .paymentAppInstanceId("payment_app_instance_id")
                    .tokenRequestorId("xxxxxxxxxxx")
                    .tokenRequestorName(DigitalWalletTokenMetadata.TokenRequestorName.APPLE_PAY)
                    .build()
            )
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.ruleResults().getOrNull())
            .containsExactly(
                TokenizationRuleResult.builder()
                    .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .explanation("explanation")
                    .name("name")
                    .result(TokenizationRuleResult.Result.APPROVED)
                    .build()
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent
                    .tokenizationDeclineReasons()
                    .getOrNull()
            )
            .containsExactly(TokenizationDeclineReason.ACCOUNT_SCORE_1)
        assertThat(digitalWalletTokenizationApprovalRequestWebhookEvent.tokenizationSource())
            .contains(
                DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                    .PUSH_PROVISION
            )
        assertThat(
                digitalWalletTokenizationApprovalRequestWebhookEvent
                    .tokenizationTfaReasons()
                    .getOrNull()
            )
            .containsExactly(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val digitalWalletTokenizationApprovalRequestWebhookEvent =
            DigitalWalletTokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerTokenizationDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent
                        .CustomerTokenizationDecision
                        .builder()
                        .outcome(
                            DigitalWalletTokenizationApprovalRequestWebhookEvent
                                .CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .eventType(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.EventType
                        .DIGITAL_WALLET_TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED
                )
                .tokenizationChannel(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationChannel
                        .DIGITAL_WALLET
                )
                .tokenizationToken("tokenization_token")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("string")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .digitalWalletTokenMetadata(
                    DigitalWalletTokenMetadata.builder()
                        .paymentAccountInfo(
                            DigitalWalletTokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    DigitalWalletTokenMetadata.PaymentAccountInfo.AccountHolderData
                                        .builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_reference")
                                .paymentAccountReference("payment_account_reference")
                                .tokenUniqueReference("token_unique_reference")
                                .build()
                        )
                        .status("status")
                        .paymentAppInstanceId("payment_app_instance_id")
                        .tokenRequestorId("xxxxxxxxxxx")
                        .tokenRequestorName(DigitalWalletTokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .explanation("explanation")
                        .name("name")
                        .result(TokenizationRuleResult.Result.APPROVED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    DigitalWalletTokenizationApprovalRequestWebhookEvent.TokenizationSource
                        .PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        val roundtrippedDigitalWalletTokenizationApprovalRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(digitalWalletTokenizationApprovalRequestWebhookEvent),
                jacksonTypeRef<DigitalWalletTokenizationApprovalRequestWebhookEvent>(),
            )

        assertThat(roundtrippedDigitalWalletTokenizationApprovalRequestWebhookEvent)
            .isEqualTo(digitalWalletTokenizationApprovalRequestWebhookEvent)
    }
}
