// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InstallmentPlanTest {

    @Test
    fun create() {
        val installmentPlan =
            InstallmentPlan.builder()
                .token("token")
                .closedAt(LocalDate.parse("2019-12-27"))
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .feeAmount(0L)
                .financialAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .installmentPlanTotal(0L)
                .addInstallment(
                    InstallmentPlan.Installment.builder()
                        .amountDue(0L)
                        .amountDueDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .amountOutstanding(0L)
                        .amountOutstandingDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .amountPaid(0L)
                        .amountPaidDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .dateAssessed(LocalDate.parse("2019-12-27"))
                        .dueDate(LocalDate.parse("2019-12-27"))
                        .installmentNum(0L)
                        .paymentDueDate(LocalDate.parse("2019-12-27"))
                        .addPayment(
                            InstallmentPlan.Installment.InstallmentPayment.builder()
                                .amount(0L)
                                .amountDetails(
                                    TransactionCategoryBalances.builder()
                                        .balanceTransfers(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .cashAdvances(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .purchases(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .date(LocalDate.parse("2019-12-27"))
                                .build()
                        )
                        .build()
                )
                .installmentsOutstanding(0L)
                .installmentsPaid(0L)
                .numInstallments(0L)
                .principalAmount(0L)
                .sourceAmounts(
                    TransactionCategoryBalances.builder()
                        .balanceTransfers(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .cashAdvances(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .purchases(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .build()
                )
                .sourceId("source_id")
                .sourceType(InstallmentPlan.InstallmentPlanSource.UNPAID_BALANCE)
                .startDate(LocalDate.parse("2019-12-27"))
                .state(InstallmentPlan.InstallmentPlanState.PENDING)
                .totalPaid(0L)
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(installmentPlan.token()).isEqualTo("token")
        assertThat(installmentPlan.closedAt()).contains(LocalDate.parse("2019-12-27"))
        assertThat(installmentPlan.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(installmentPlan.feeAmount()).isEqualTo(0L)
        assertThat(installmentPlan.financialAccountToken())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(installmentPlan.installmentPlanTotal()).isEqualTo(0L)
        assertThat(installmentPlan.installments())
            .containsExactly(
                InstallmentPlan.Installment.builder()
                    .amountDue(0L)
                    .amountDueDetails(
                        TransactionCategoryBalances.builder()
                            .balanceTransfers(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .cashAdvances(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .purchases(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .build()
                    )
                    .amountOutstanding(0L)
                    .amountOutstandingDetails(
                        TransactionCategoryBalances.builder()
                            .balanceTransfers(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .cashAdvances(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .purchases(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .build()
                    )
                    .amountPaid(0L)
                    .amountPaidDetails(
                        TransactionCategoryBalances.builder()
                            .balanceTransfers(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .cashAdvances(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .purchases(
                                CategoryBalances.builder()
                                    .fees(0L)
                                    .interest(0L)
                                    .principal(0L)
                                    .build()
                            )
                            .build()
                    )
                    .dateAssessed(LocalDate.parse("2019-12-27"))
                    .dueDate(LocalDate.parse("2019-12-27"))
                    .installmentNum(0L)
                    .paymentDueDate(LocalDate.parse("2019-12-27"))
                    .addPayment(
                        InstallmentPlan.Installment.InstallmentPayment.builder()
                            .amount(0L)
                            .amountDetails(
                                TransactionCategoryBalances.builder()
                                    .balanceTransfers(
                                        CategoryBalances.builder()
                                            .fees(0L)
                                            .interest(0L)
                                            .principal(0L)
                                            .build()
                                    )
                                    .cashAdvances(
                                        CategoryBalances.builder()
                                            .fees(0L)
                                            .interest(0L)
                                            .principal(0L)
                                            .build()
                                    )
                                    .purchases(
                                        CategoryBalances.builder()
                                            .fees(0L)
                                            .interest(0L)
                                            .principal(0L)
                                            .build()
                                    )
                                    .build()
                            )
                            .date(LocalDate.parse("2019-12-27"))
                            .build()
                    )
                    .build()
            )
        assertThat(installmentPlan.installmentsOutstanding()).isEqualTo(0L)
        assertThat(installmentPlan.installmentsPaid()).isEqualTo(0L)
        assertThat(installmentPlan.numInstallments()).isEqualTo(0L)
        assertThat(installmentPlan.principalAmount()).isEqualTo(0L)
        assertThat(installmentPlan.sourceAmounts())
            .contains(
                TransactionCategoryBalances.builder()
                    .balanceTransfers(
                        CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                    )
                    .cashAdvances(
                        CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                    )
                    .purchases(
                        CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                    )
                    .build()
            )
        assertThat(installmentPlan.sourceId()).isEqualTo("source_id")
        assertThat(installmentPlan.sourceType())
            .isEqualTo(InstallmentPlan.InstallmentPlanSource.UNPAID_BALANCE)
        assertThat(installmentPlan.startDate()).isEqualTo(LocalDate.parse("2019-12-27"))
        assertThat(installmentPlan.state()).isEqualTo(InstallmentPlan.InstallmentPlanState.PENDING)
        assertThat(installmentPlan.totalPaid()).isEqualTo(0L)
        assertThat(installmentPlan.updated())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val installmentPlan =
            InstallmentPlan.builder()
                .token("token")
                .closedAt(LocalDate.parse("2019-12-27"))
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .feeAmount(0L)
                .financialAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .installmentPlanTotal(0L)
                .addInstallment(
                    InstallmentPlan.Installment.builder()
                        .amountDue(0L)
                        .amountDueDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .amountOutstanding(0L)
                        .amountOutstandingDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .amountPaid(0L)
                        .amountPaidDetails(
                            TransactionCategoryBalances.builder()
                                .balanceTransfers(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .cashAdvances(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .purchases(
                                    CategoryBalances.builder()
                                        .fees(0L)
                                        .interest(0L)
                                        .principal(0L)
                                        .build()
                                )
                                .build()
                        )
                        .dateAssessed(LocalDate.parse("2019-12-27"))
                        .dueDate(LocalDate.parse("2019-12-27"))
                        .installmentNum(0L)
                        .paymentDueDate(LocalDate.parse("2019-12-27"))
                        .addPayment(
                            InstallmentPlan.Installment.InstallmentPayment.builder()
                                .amount(0L)
                                .amountDetails(
                                    TransactionCategoryBalances.builder()
                                        .balanceTransfers(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .cashAdvances(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .purchases(
                                            CategoryBalances.builder()
                                                .fees(0L)
                                                .interest(0L)
                                                .principal(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .date(LocalDate.parse("2019-12-27"))
                                .build()
                        )
                        .build()
                )
                .installmentsOutstanding(0L)
                .installmentsPaid(0L)
                .numInstallments(0L)
                .principalAmount(0L)
                .sourceAmounts(
                    TransactionCategoryBalances.builder()
                        .balanceTransfers(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .cashAdvances(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .purchases(
                            CategoryBalances.builder().fees(0L).interest(0L).principal(0L).build()
                        )
                        .build()
                )
                .sourceId("source_id")
                .sourceType(InstallmentPlan.InstallmentPlanSource.UNPAID_BALANCE)
                .startDate(LocalDate.parse("2019-12-27"))
                .state(InstallmentPlan.InstallmentPlanState.PENDING)
                .totalPaid(0L)
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedInstallmentPlan =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(installmentPlan),
                jacksonTypeRef<InstallmentPlan>(),
            )

        assertThat(roundtrippedInstallmentPlan).isEqualTo(installmentPlan)
    }
}
