// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PaymentRetryResponseTest {

    @Test
    fun create() {
        val paymentRetryResponse =
            PaymentRetryResponse.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .category(Payment.TransactionCategory.ACH)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .descriptor("descriptor")
                .direction(Payment.Direction.CREDIT)
                .addEvent(
                    Payment.PaymentEvent.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .amount(0L)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .result(Payment.PaymentEvent.Result.APPROVED)
                        .type(Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_CANCELLED)
                        .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                        .build()
                )
                .family(Payment.Family.PAYMENT)
                .financialAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .method(Payment.Method.ACH_NEXT_DAY)
                .methodAttributes(
                    Payment.MethodAttributes.AchMethodAttributes.builder()
                        .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                        .addenda("addenda")
                        .companyId("company_id")
                        .receiptRoutingNumber("receipt_routing_number")
                        .retries(0L)
                        .returnReasonCode("return_reason_code")
                        .addTraceNumber("string")
                        .build()
                )
                .pendingAmount(200L)
                .relatedAccountTokens(
                    Payment.RelatedAccountTokens.builder()
                        .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .result(Payment.TransactionResult.APPROVED)
                .settledAmount(500L)
                .source(Payment.Source.LITHIC)
                .status(Payment.TransactionStatus.PENDING)
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .currency("USD")
                .expectedReleaseDate(LocalDate.parse("2019-12-27"))
                .externalBankAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .type(Payment.TransferType.ORIGINATION_CREDIT)
                .userDefinedId("user_defined_id")
                .balance(
                    Balance.builder()
                        .availableAmount(0L)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .financialAccountToken("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .financialAccountType(Balance.FinancialAccountType.ISSUING)
                        .lastTransactionEventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .lastTransactionToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .pendingAmount(0L)
                        .totalAmount(0L)
                        .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        assertThat(paymentRetryResponse.token()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(paymentRetryResponse.category()).isEqualTo(Payment.TransactionCategory.ACH)
        assertThat(paymentRetryResponse.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(paymentRetryResponse.descriptor()).isEqualTo("descriptor")
        assertThat(paymentRetryResponse.direction()).isEqualTo(Payment.Direction.CREDIT)
        assertThat(paymentRetryResponse.events())
            .containsExactly(
                Payment.PaymentEvent.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .amount(0L)
                    .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .result(Payment.PaymentEvent.Result.APPROVED)
                    .type(Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_CANCELLED)
                    .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                    .build()
            )
        assertThat(paymentRetryResponse.family()).isEqualTo(Payment.Family.PAYMENT)
        assertThat(paymentRetryResponse.financialAccountToken())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(paymentRetryResponse.method()).isEqualTo(Payment.Method.ACH_NEXT_DAY)
        assertThat(paymentRetryResponse.methodAttributes())
            .isEqualTo(
                Payment.MethodAttributes.ofAch(
                    Payment.MethodAttributes.AchMethodAttributes.builder()
                        .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                        .addenda("addenda")
                        .companyId("company_id")
                        .receiptRoutingNumber("receipt_routing_number")
                        .retries(0L)
                        .returnReasonCode("return_reason_code")
                        .addTraceNumber("string")
                        .build()
                )
            )
        assertThat(paymentRetryResponse.pendingAmount()).isEqualTo(200L)
        assertThat(paymentRetryResponse.relatedAccountTokens())
            .isEqualTo(
                Payment.RelatedAccountTokens.builder()
                    .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(paymentRetryResponse.result()).isEqualTo(Payment.TransactionResult.APPROVED)
        assertThat(paymentRetryResponse.settledAmount()).isEqualTo(500L)
        assertThat(paymentRetryResponse.source()).isEqualTo(Payment.Source.LITHIC)
        assertThat(paymentRetryResponse.status()).isEqualTo(Payment.TransactionStatus.PENDING)
        assertThat(paymentRetryResponse.updated())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(paymentRetryResponse.currency()).contains("USD")
        assertThat(paymentRetryResponse.expectedReleaseDate())
            .contains(LocalDate.parse("2019-12-27"))
        assertThat(paymentRetryResponse.externalBankAccountToken())
            .contains("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(paymentRetryResponse.type()).contains(Payment.TransferType.ORIGINATION_CREDIT)
        assertThat(paymentRetryResponse.userDefinedId()).contains("user_defined_id")
        assertThat(paymentRetryResponse.balance())
            .contains(
                Balance.builder()
                    .availableAmount(0L)
                    .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .financialAccountToken("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                    .financialAccountType(Balance.FinancialAccountType.ISSUING)
                    .lastTransactionEventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .lastTransactionToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .pendingAmount(0L)
                    .totalAmount(0L)
                    .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val paymentRetryResponse =
            PaymentRetryResponse.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .category(Payment.TransactionCategory.ACH)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .descriptor("descriptor")
                .direction(Payment.Direction.CREDIT)
                .addEvent(
                    Payment.PaymentEvent.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .amount(0L)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .result(Payment.PaymentEvent.Result.APPROVED)
                        .type(Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_CANCELLED)
                        .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                        .build()
                )
                .family(Payment.Family.PAYMENT)
                .financialAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .method(Payment.Method.ACH_NEXT_DAY)
                .methodAttributes(
                    Payment.MethodAttributes.AchMethodAttributes.builder()
                        .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                        .addenda("addenda")
                        .companyId("company_id")
                        .receiptRoutingNumber("receipt_routing_number")
                        .retries(0L)
                        .returnReasonCode("return_reason_code")
                        .addTraceNumber("string")
                        .build()
                )
                .pendingAmount(200L)
                .relatedAccountTokens(
                    Payment.RelatedAccountTokens.builder()
                        .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .result(Payment.TransactionResult.APPROVED)
                .settledAmount(500L)
                .source(Payment.Source.LITHIC)
                .status(Payment.TransactionStatus.PENDING)
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .currency("USD")
                .expectedReleaseDate(LocalDate.parse("2019-12-27"))
                .externalBankAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .type(Payment.TransferType.ORIGINATION_CREDIT)
                .userDefinedId("user_defined_id")
                .balance(
                    Balance.builder()
                        .availableAmount(0L)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .financialAccountToken("3fa85f64-5717-4562-b3fc-2c963f66afa6")
                        .financialAccountType(Balance.FinancialAccountType.ISSUING)
                        .lastTransactionEventToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .lastTransactionToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .pendingAmount(0L)
                        .totalAmount(0L)
                        .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        val roundtrippedPaymentRetryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(paymentRetryResponse),
                jacksonTypeRef<PaymentRetryResponse>(),
            )

        assertThat(roundtrippedPaymentRetryResponse).isEqualTo(paymentRetryResponse)
    }
}
