// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PaymentListPageResponseTest {

    @Test
    fun create() {
        val paymentListPageResponse =
            PaymentListPageResponse.builder()
                .addData(
                    Payment.builder()
                        .token("bd4efddb-771b-49e3-9af9-49b077ab5eb8")
                        .category(Payment.TransactionCategory.ACH)
                        .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                        .descriptor("ach_origination_credit")
                        .direction(Payment.Direction.CREDIT)
                        .addEvent(
                            Payment.PaymentEvent.builder()
                                .token("327dccc3-fe42-54d2-962c-7f8135805464")
                                .amount(-1588L)
                                .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                                .result(Payment.PaymentEvent.Result.APPROVED)
                                .type(
                                    Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_INITIATED
                                )
                                .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                                .build()
                        )
                        .addEvent(
                            Payment.PaymentEvent.builder()
                                .token("f9165477-7cfc-53c6-98f1-84e9ec856a60")
                                .amount(-1588L)
                                .created(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                                .result(Payment.PaymentEvent.Result.APPROVED)
                                .type(
                                    Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_REVIEWED
                                )
                                .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                                .build()
                        )
                        .family(Payment.Family.PAYMENT)
                        .financialAccountToken("35b0c466-a3e3-519a-9549-ead6a6a2277d")
                        .method(Payment.Method.ACH_NEXT_DAY)
                        .methodAttributes(
                            Payment.MethodAttributes.AchMethodAttributes.builder()
                                .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                                .achHoldPeriod(1L)
                                .addenda(null)
                                .companyId("1111111111")
                                .receiptRoutingNumber(null)
                                .retries(0L)
                                .returnReasonCode(null)
                                .addTraceNumber("string")
                                .build()
                        )
                        .pendingAmount(-1588L)
                        .relatedAccountTokens(
                            Payment.RelatedAccountTokens.builder()
                                .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .result(Payment.TransactionResult.APPROVED)
                        .settledAmount(0L)
                        .source(Payment.Source.LITHIC)
                        .status(Payment.TransactionStatus.PENDING)
                        .updated(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                        .currency("USD")
                        .expectedReleaseDate(null)
                        .externalBankAccountToken("feb4fee1-2414-4c38-a5f6-9deac293c8f4")
                        .type(Payment.TransferType.ORIGINATION_CREDIT)
                        .userDefinedId(null)
                        .build()
                )
                .hasMore(true)
                .build()

        assertThat(paymentListPageResponse.data())
            .containsExactly(
                Payment.builder()
                    .token("bd4efddb-771b-49e3-9af9-49b077ab5eb8")
                    .category(Payment.TransactionCategory.ACH)
                    .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                    .descriptor("ach_origination_credit")
                    .direction(Payment.Direction.CREDIT)
                    .addEvent(
                        Payment.PaymentEvent.builder()
                            .token("327dccc3-fe42-54d2-962c-7f8135805464")
                            .amount(-1588L)
                            .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                            .result(Payment.PaymentEvent.Result.APPROVED)
                            .type(Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_INITIATED)
                            .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                            .build()
                    )
                    .addEvent(
                        Payment.PaymentEvent.builder()
                            .token("f9165477-7cfc-53c6-98f1-84e9ec856a60")
                            .amount(-1588L)
                            .created(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                            .result(Payment.PaymentEvent.Result.APPROVED)
                            .type(Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_REVIEWED)
                            .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                            .build()
                    )
                    .family(Payment.Family.PAYMENT)
                    .financialAccountToken("35b0c466-a3e3-519a-9549-ead6a6a2277d")
                    .method(Payment.Method.ACH_NEXT_DAY)
                    .methodAttributes(
                        Payment.MethodAttributes.AchMethodAttributes.builder()
                            .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                            .achHoldPeriod(1L)
                            .addenda(null)
                            .companyId("1111111111")
                            .receiptRoutingNumber(null)
                            .retries(0L)
                            .returnReasonCode(null)
                            .addTraceNumber("string")
                            .build()
                    )
                    .pendingAmount(-1588L)
                    .relatedAccountTokens(
                        Payment.RelatedAccountTokens.builder()
                            .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .result(Payment.TransactionResult.APPROVED)
                    .settledAmount(0L)
                    .source(Payment.Source.LITHIC)
                    .status(Payment.TransactionStatus.PENDING)
                    .updated(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                    .currency("USD")
                    .expectedReleaseDate(null)
                    .externalBankAccountToken("feb4fee1-2414-4c38-a5f6-9deac293c8f4")
                    .type(Payment.TransferType.ORIGINATION_CREDIT)
                    .userDefinedId(null)
                    .build()
            )
        assertThat(paymentListPageResponse.hasMore()).isEqualTo(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val paymentListPageResponse =
            PaymentListPageResponse.builder()
                .addData(
                    Payment.builder()
                        .token("bd4efddb-771b-49e3-9af9-49b077ab5eb8")
                        .category(Payment.TransactionCategory.ACH)
                        .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                        .descriptor("ach_origination_credit")
                        .direction(Payment.Direction.CREDIT)
                        .addEvent(
                            Payment.PaymentEvent.builder()
                                .token("327dccc3-fe42-54d2-962c-7f8135805464")
                                .amount(-1588L)
                                .created(OffsetDateTime.parse("2025-10-27T20:12:22Z"))
                                .result(Payment.PaymentEvent.Result.APPROVED)
                                .type(
                                    Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_INITIATED
                                )
                                .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                                .build()
                        )
                        .addEvent(
                            Payment.PaymentEvent.builder()
                                .token("f9165477-7cfc-53c6-98f1-84e9ec856a60")
                                .amount(-1588L)
                                .created(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                                .result(Payment.PaymentEvent.Result.APPROVED)
                                .type(
                                    Payment.PaymentEvent.PaymentEventType.ACH_ORIGINATION_REVIEWED
                                )
                                .addDetailedResult(Payment.PaymentEvent.DetailedResult.APPROVED)
                                .build()
                        )
                        .family(Payment.Family.PAYMENT)
                        .financialAccountToken("35b0c466-a3e3-519a-9549-ead6a6a2277d")
                        .method(Payment.Method.ACH_NEXT_DAY)
                        .methodAttributes(
                            Payment.MethodAttributes.AchMethodAttributes.builder()
                                .secCode(Payment.MethodAttributes.AchMethodAttributes.SecCode.CCD)
                                .achHoldPeriod(1L)
                                .addenda(null)
                                .companyId("1111111111")
                                .receiptRoutingNumber(null)
                                .retries(0L)
                                .returnReasonCode(null)
                                .addTraceNumber("string")
                                .build()
                        )
                        .pendingAmount(-1588L)
                        .relatedAccountTokens(
                            Payment.RelatedAccountTokens.builder()
                                .accountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .businessAccountToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .result(Payment.TransactionResult.APPROVED)
                        .settledAmount(0L)
                        .source(Payment.Source.LITHIC)
                        .status(Payment.TransactionStatus.PENDING)
                        .updated(OffsetDateTime.parse("2025-10-27T20:12:25Z"))
                        .currency("USD")
                        .expectedReleaseDate(null)
                        .externalBankAccountToken("feb4fee1-2414-4c38-a5f6-9deac293c8f4")
                        .type(Payment.TransferType.ORIGINATION_CREDIT)
                        .userDefinedId(null)
                        .build()
                )
                .hasMore(true)
                .build()

        val roundtrippedPaymentListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(paymentListPageResponse),
                jacksonTypeRef<PaymentListPageResponse>(),
            )

        assertThat(roundtrippedPaymentListPageResponse).isEqualTo(paymentListPageResponse)
    }
}
