// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ReportSettlementNetworkTotalListPageResponseTest {

    @Test
    fun create() {
        val reportSettlementNetworkTotalListPageResponse =
            ReportSettlementNetworkTotalListPageResponse.builder()
                .data(
                    listOf(
                        NetworkTotalListResponse.builder()
                            .token("12cf7505-06a8-435e-b1c7-4c430d02f6c3")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(85L)
                                    .visaCharges(10L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("CAD")
                            .institutionId("1000000000")
                            .network(NetworkTotalListResponse.Network.VISA)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("1000000001")
                            .settlementService("015")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(0L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("0604c316-17f0-456d-9ac7-7d94252acb1a")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(200L)
                                    .interchangeFees(-50L)
                                    .netSettlement(160L)
                                    .visaCharges(10L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("1000000000")
                            .network(NetworkTotalListResponse.Network.INTERLINK)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("1000000001")
                            .settlementService("001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(0L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("700a1c78-04ed-47e2-8160-b1e18914ec7b")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(75L)
                                    .visaCharges(0L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("031511")
                            .network(NetworkTotalListResponse.Network.MASTERCARD)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("031511")
                            .settlementService("US00000001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(1L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("e05d5448-210e-4cc3-bd0d-d54d3c6c9a9f")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(75L)
                                    .visaCharges(0L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("031511")
                            .network(NetworkTotalListResponse.Network.MASTERCARD)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("031511")
                            .settlementService("US00000001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(2L)
                            .build(),
                    )
                )
                .hasMore(false)
                .build()

        assertThat(reportSettlementNetworkTotalListPageResponse.data())
            .containsExactly(
                NetworkTotalListResponse.builder()
                    .token("12cf7505-06a8-435e-b1c7-4c430d02f6c3")
                    .amounts(
                        NetworkTotalListResponse.Amounts.builder()
                            .grossSettlement(100L)
                            .interchangeFees(-25L)
                            .netSettlement(85L)
                            .visaCharges(10L)
                            .build()
                    )
                    .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .currency("CAD")
                    .institutionId("1000000000")
                    .network(NetworkTotalListResponse.Network.VISA)
                    .reportDate(LocalDate.parse("2025-02-25"))
                    .settlementInstitutionId("1000000001")
                    .settlementService("015")
                    .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .cycle(0L)
                    .build(),
                NetworkTotalListResponse.builder()
                    .token("0604c316-17f0-456d-9ac7-7d94252acb1a")
                    .amounts(
                        NetworkTotalListResponse.Amounts.builder()
                            .grossSettlement(200L)
                            .interchangeFees(-50L)
                            .netSettlement(160L)
                            .visaCharges(10L)
                            .build()
                    )
                    .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .currency("USD")
                    .institutionId("1000000000")
                    .network(NetworkTotalListResponse.Network.INTERLINK)
                    .reportDate(LocalDate.parse("2025-02-25"))
                    .settlementInstitutionId("1000000001")
                    .settlementService("001")
                    .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .cycle(0L)
                    .build(),
                NetworkTotalListResponse.builder()
                    .token("700a1c78-04ed-47e2-8160-b1e18914ec7b")
                    .amounts(
                        NetworkTotalListResponse.Amounts.builder()
                            .grossSettlement(100L)
                            .interchangeFees(-25L)
                            .netSettlement(75L)
                            .visaCharges(0L)
                            .build()
                    )
                    .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .currency("USD")
                    .institutionId("031511")
                    .network(NetworkTotalListResponse.Network.MASTERCARD)
                    .reportDate(LocalDate.parse("2025-02-25"))
                    .settlementInstitutionId("031511")
                    .settlementService("US00000001")
                    .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .cycle(1L)
                    .build(),
                NetworkTotalListResponse.builder()
                    .token("e05d5448-210e-4cc3-bd0d-d54d3c6c9a9f")
                    .amounts(
                        NetworkTotalListResponse.Amounts.builder()
                            .grossSettlement(100L)
                            .interchangeFees(-25L)
                            .netSettlement(75L)
                            .visaCharges(0L)
                            .build()
                    )
                    .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .currency("USD")
                    .institutionId("031511")
                    .network(NetworkTotalListResponse.Network.MASTERCARD)
                    .reportDate(LocalDate.parse("2025-02-25"))
                    .settlementInstitutionId("031511")
                    .settlementService("US00000001")
                    .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                    .cycle(2L)
                    .build(),
            )
        assertThat(reportSettlementNetworkTotalListPageResponse.hasMore()).isEqualTo(false)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val reportSettlementNetworkTotalListPageResponse =
            ReportSettlementNetworkTotalListPageResponse.builder()
                .data(
                    listOf(
                        NetworkTotalListResponse.builder()
                            .token("12cf7505-06a8-435e-b1c7-4c430d02f6c3")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(85L)
                                    .visaCharges(10L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("CAD")
                            .institutionId("1000000000")
                            .network(NetworkTotalListResponse.Network.VISA)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("1000000001")
                            .settlementService("015")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(0L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("0604c316-17f0-456d-9ac7-7d94252acb1a")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(200L)
                                    .interchangeFees(-50L)
                                    .netSettlement(160L)
                                    .visaCharges(10L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("1000000000")
                            .network(NetworkTotalListResponse.Network.INTERLINK)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("1000000001")
                            .settlementService("001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(0L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("700a1c78-04ed-47e2-8160-b1e18914ec7b")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(75L)
                                    .visaCharges(0L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("031511")
                            .network(NetworkTotalListResponse.Network.MASTERCARD)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("031511")
                            .settlementService("US00000001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(1L)
                            .build(),
                        NetworkTotalListResponse.builder()
                            .token("e05d5448-210e-4cc3-bd0d-d54d3c6c9a9f")
                            .amounts(
                                NetworkTotalListResponse.Amounts.builder()
                                    .grossSettlement(100L)
                                    .interchangeFees(-25L)
                                    .netSettlement(75L)
                                    .visaCharges(0L)
                                    .build()
                            )
                            .created(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .currency("USD")
                            .institutionId("031511")
                            .network(NetworkTotalListResponse.Network.MASTERCARD)
                            .reportDate(LocalDate.parse("2025-02-25"))
                            .settlementInstitutionId("031511")
                            .settlementService("US00000001")
                            .updated(OffsetDateTime.parse("2025-02-25T13:07:31.419631Z"))
                            .cycle(2L)
                            .build(),
                    )
                )
                .hasMore(false)
                .build()

        val roundtrippedReportSettlementNetworkTotalListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(reportSettlementNetworkTotalListPageResponse),
                jacksonTypeRef<ReportSettlementNetworkTotalListPageResponse>(),
            )

        assertThat(roundtrippedReportSettlementNetworkTotalListPageResponse)
            .isEqualTo(reportSettlementNetworkTotalListPageResponse)
    }
}
