// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ThreeDSAuthenticationTest {

    @Test
    fun create() {
        val threeDSAuthentication =
            ThreeDSAuthentication.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountType(ThreeDSAuthentication.AccountType.CREDIT)
                .authenticationResult(ThreeDSAuthentication.AuthenticationResult.DECLINE)
                .cardExpiryCheck(ThreeDSAuthentication.CardExpiryCheck.MATCH)
                .cardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .cardholder(
                    ThreeDSAuthentication.Cardholder.builder()
                        .addressMatch(true)
                        .addressOnFileMatch(
                            ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH
                        )
                        .billingAddress(
                            ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                                .address1("address1")
                                .address2("address2")
                                .address3("address3")
                                .city("city")
                                .country("xxx")
                                .postalCode("postal_code")
                                .build()
                        )
                        .email("x")
                        .name("x")
                        .phoneNumberHome("x")
                        .phoneNumberMobile("x")
                        .phoneNumberWork("x")
                        .shippingAddress(
                            ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                                .address1("address1")
                                .address2("address2")
                                .address3("address3")
                                .city("city")
                                .country("xxx")
                                .postalCode("postal_code")
                                .build()
                        )
                        .build()
                )
                .channel(ThreeDSAuthentication.Channel.APP_BASED)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    ThreeDSAuthentication.Merchant.builder()
                        .riskIndicator(
                            ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                                .deliveryEmailAddress("delivery_email_address")
                                .deliveryTimeFrame(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.DeliveryTimeFrame
                                        .ELECTRONIC_DELIVERY
                                )
                                .giftCardAmount(0L)
                                .giftCardCount(0L)
                                .giftCardCurrency("xxx")
                                .orderAvailability(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.OrderAvailability
                                        .FUTURE_AVAILABILITY
                                )
                                .preOrderAvailableDate(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .reorderItems(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.ReorderItems
                                        .FIRST_TIME_ORDERED
                                )
                                .shippingMethod(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.ShippingMethod
                                        .DIGITAL_GOODS
                                )
                                .build()
                        )
                        .id("id")
                        .country("xxx")
                        .mcc("xxxx")
                        .name("name")
                        .build()
                )
                .messageCategory(ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION)
                .threeDSRequestorChallengeIndicator(
                    ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE
                )
                .additionalData(
                    ThreeDSAuthentication.AdditionalData.builder()
                        .networkDecision(
                            ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK
                        )
                        .networkRiskScore(0L)
                        .build()
                )
                .app(
                    ThreeDSAuthentication.App.builder()
                        .device("device")
                        .deviceInfo("device_info")
                        .ip("ip")
                        .latitude(-90.0)
                        .locale("locale")
                        .longitude(-180.0)
                        .os("os")
                        .platform("platform")
                        .screenHeight(0L)
                        .screenWidth(0L)
                        .timeZone("time_zone")
                        .build()
                )
                .authenticationRequestType(ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD)
                .browser(
                    ThreeDSAuthentication.Browser.builder()
                        .acceptHeader("accept_header")
                        .ip("ip")
                        .javaEnabled(true)
                        .javascriptEnabled(true)
                        .language("language")
                        .timeZone("time_zone")
                        .userAgent("user_agent")
                        .build()
                )
                .challengeMetadata(
                    ThreeDSAuthentication.ChallengeMetadata.builder()
                        .methodType(ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP)
                        .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                        .phoneNumber("phone_number")
                        .build()
                )
                .challengeOrchestratedBy(ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC)
                .decisionMadeBy(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
                .threeRiRequestType(ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION)
                .transaction(
                    ThreeDSAuthentication.Transaction.builder()
                        .amount(0.0)
                        .cardholderAmount(0.0)
                        .currency("xxx")
                        .currencyExponent(0.0)
                        .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                        .build()
                )
                .build()

        assertThat(threeDSAuthentication.token()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(threeDSAuthentication.accountType())
            .contains(ThreeDSAuthentication.AccountType.CREDIT)
        assertThat(threeDSAuthentication.authenticationResult())
            .isEqualTo(ThreeDSAuthentication.AuthenticationResult.DECLINE)
        assertThat(threeDSAuthentication.cardExpiryCheck())
            .isEqualTo(ThreeDSAuthentication.CardExpiryCheck.MATCH)
        assertThat(threeDSAuthentication.cardToken())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(threeDSAuthentication.cardholder())
            .isEqualTo(
                ThreeDSAuthentication.Cardholder.builder()
                    .addressMatch(true)
                    .addressOnFileMatch(ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH)
                    .billingAddress(
                        ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                            .address1("address1")
                            .address2("address2")
                            .address3("address3")
                            .city("city")
                            .country("xxx")
                            .postalCode("postal_code")
                            .build()
                    )
                    .email("x")
                    .name("x")
                    .phoneNumberHome("x")
                    .phoneNumberMobile("x")
                    .phoneNumberWork("x")
                    .shippingAddress(
                        ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                            .address1("address1")
                            .address2("address2")
                            .address3("address3")
                            .city("city")
                            .country("xxx")
                            .postalCode("postal_code")
                            .build()
                    )
                    .build()
            )
        assertThat(threeDSAuthentication.channel())
            .isEqualTo(ThreeDSAuthentication.Channel.APP_BASED)
        assertThat(threeDSAuthentication.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(threeDSAuthentication.merchant())
            .isEqualTo(
                ThreeDSAuthentication.Merchant.builder()
                    .riskIndicator(
                        ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                            .deliveryEmailAddress("delivery_email_address")
                            .deliveryTimeFrame(
                                ThreeDSAuthentication.Merchant.RiskIndicator.DeliveryTimeFrame
                                    .ELECTRONIC_DELIVERY
                            )
                            .giftCardAmount(0L)
                            .giftCardCount(0L)
                            .giftCardCurrency("xxx")
                            .orderAvailability(
                                ThreeDSAuthentication.Merchant.RiskIndicator.OrderAvailability
                                    .FUTURE_AVAILABILITY
                            )
                            .preOrderAvailableDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .reorderItems(
                                ThreeDSAuthentication.Merchant.RiskIndicator.ReorderItems
                                    .FIRST_TIME_ORDERED
                            )
                            .shippingMethod(
                                ThreeDSAuthentication.Merchant.RiskIndicator.ShippingMethod
                                    .DIGITAL_GOODS
                            )
                            .build()
                    )
                    .id("id")
                    .country("xxx")
                    .mcc("xxxx")
                    .name("name")
                    .build()
            )
        assertThat(threeDSAuthentication.messageCategory())
            .isEqualTo(ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION)
        assertThat(threeDSAuthentication.threeDSRequestorChallengeIndicator())
            .isEqualTo(ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE)
        assertThat(threeDSAuthentication.additionalData())
            .contains(
                ThreeDSAuthentication.AdditionalData.builder()
                    .networkDecision(ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK)
                    .networkRiskScore(0L)
                    .build()
            )
        assertThat(threeDSAuthentication.app())
            .contains(
                ThreeDSAuthentication.App.builder()
                    .device("device")
                    .deviceInfo("device_info")
                    .ip("ip")
                    .latitude(-90.0)
                    .locale("locale")
                    .longitude(-180.0)
                    .os("os")
                    .platform("platform")
                    .screenHeight(0L)
                    .screenWidth(0L)
                    .timeZone("time_zone")
                    .build()
            )
        assertThat(threeDSAuthentication.authenticationRequestType())
            .contains(ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD)
        assertThat(threeDSAuthentication.browser())
            .contains(
                ThreeDSAuthentication.Browser.builder()
                    .acceptHeader("accept_header")
                    .ip("ip")
                    .javaEnabled(true)
                    .javascriptEnabled(true)
                    .language("language")
                    .timeZone("time_zone")
                    .userAgent("user_agent")
                    .build()
            )
        assertThat(threeDSAuthentication.challengeMetadata())
            .contains(
                ThreeDSAuthentication.ChallengeMetadata.builder()
                    .methodType(ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP)
                    .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                    .phoneNumber("phone_number")
                    .build()
            )
        assertThat(threeDSAuthentication.challengeOrchestratedBy())
            .contains(ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC)
        assertThat(threeDSAuthentication.decisionMadeBy())
            .contains(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
        assertThat(threeDSAuthentication.threeRiRequestType())
            .contains(ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION)
        assertThat(threeDSAuthentication.transaction())
            .contains(
                ThreeDSAuthentication.Transaction.builder()
                    .amount(0.0)
                    .cardholderAmount(0.0)
                    .currency("xxx")
                    .currencyExponent(0.0)
                    .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val threeDSAuthentication =
            ThreeDSAuthentication.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountType(ThreeDSAuthentication.AccountType.CREDIT)
                .authenticationResult(ThreeDSAuthentication.AuthenticationResult.DECLINE)
                .cardExpiryCheck(ThreeDSAuthentication.CardExpiryCheck.MATCH)
                .cardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .cardholder(
                    ThreeDSAuthentication.Cardholder.builder()
                        .addressMatch(true)
                        .addressOnFileMatch(
                            ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH
                        )
                        .billingAddress(
                            ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                                .address1("address1")
                                .address2("address2")
                                .address3("address3")
                                .city("city")
                                .country("xxx")
                                .postalCode("postal_code")
                                .build()
                        )
                        .email("x")
                        .name("x")
                        .phoneNumberHome("x")
                        .phoneNumberMobile("x")
                        .phoneNumberWork("x")
                        .shippingAddress(
                            ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                                .address1("address1")
                                .address2("address2")
                                .address3("address3")
                                .city("city")
                                .country("xxx")
                                .postalCode("postal_code")
                                .build()
                        )
                        .build()
                )
                .channel(ThreeDSAuthentication.Channel.APP_BASED)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .merchant(
                    ThreeDSAuthentication.Merchant.builder()
                        .riskIndicator(
                            ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                                .deliveryEmailAddress("delivery_email_address")
                                .deliveryTimeFrame(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.DeliveryTimeFrame
                                        .ELECTRONIC_DELIVERY
                                )
                                .giftCardAmount(0L)
                                .giftCardCount(0L)
                                .giftCardCurrency("xxx")
                                .orderAvailability(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.OrderAvailability
                                        .FUTURE_AVAILABILITY
                                )
                                .preOrderAvailableDate(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .reorderItems(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.ReorderItems
                                        .FIRST_TIME_ORDERED
                                )
                                .shippingMethod(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.ShippingMethod
                                        .DIGITAL_GOODS
                                )
                                .build()
                        )
                        .id("id")
                        .country("xxx")
                        .mcc("xxxx")
                        .name("name")
                        .build()
                )
                .messageCategory(ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION)
                .threeDSRequestorChallengeIndicator(
                    ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE
                )
                .additionalData(
                    ThreeDSAuthentication.AdditionalData.builder()
                        .networkDecision(
                            ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK
                        )
                        .networkRiskScore(0L)
                        .build()
                )
                .app(
                    ThreeDSAuthentication.App.builder()
                        .device("device")
                        .deviceInfo("device_info")
                        .ip("ip")
                        .latitude(-90.0)
                        .locale("locale")
                        .longitude(-180.0)
                        .os("os")
                        .platform("platform")
                        .screenHeight(0L)
                        .screenWidth(0L)
                        .timeZone("time_zone")
                        .build()
                )
                .authenticationRequestType(ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD)
                .browser(
                    ThreeDSAuthentication.Browser.builder()
                        .acceptHeader("accept_header")
                        .ip("ip")
                        .javaEnabled(true)
                        .javascriptEnabled(true)
                        .language("language")
                        .timeZone("time_zone")
                        .userAgent("user_agent")
                        .build()
                )
                .challengeMetadata(
                    ThreeDSAuthentication.ChallengeMetadata.builder()
                        .methodType(ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP)
                        .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                        .phoneNumber("phone_number")
                        .build()
                )
                .challengeOrchestratedBy(ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC)
                .decisionMadeBy(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
                .threeRiRequestType(ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION)
                .transaction(
                    ThreeDSAuthentication.Transaction.builder()
                        .amount(0.0)
                        .cardholderAmount(0.0)
                        .currency("xxx")
                        .currencyExponent(0.0)
                        .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                        .build()
                )
                .build()

        val roundtrippedThreeDSAuthentication =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(threeDSAuthentication),
                jacksonTypeRef<ThreeDSAuthentication>(),
            )

        assertThat(roundtrippedThreeDSAuthentication).isEqualTo(threeDSAuthentication)
    }
}
