// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ThreeDSAuthenticationChallengeWebhookEventTest {

    @Test
    fun create() {
        val threeDSAuthenticationChallengeWebhookEvent =
            ThreeDSAuthenticationChallengeWebhookEvent.builder()
                .authenticationObject(
                    ThreeDSAuthentication.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .accountType(ThreeDSAuthentication.AccountType.CREDIT)
                        .authenticationResult(ThreeDSAuthentication.AuthenticationResult.DECLINE)
                        .cardExpiryCheck(ThreeDSAuthentication.CardExpiryCheck.MATCH)
                        .cardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .cardholder(
                            ThreeDSAuthentication.Cardholder.builder()
                                .addressMatch(true)
                                .addressOnFileMatch(
                                    ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH
                                )
                                .billingAddress(
                                    ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                                        .address1("address1")
                                        .address2("address2")
                                        .address3("address3")
                                        .city("city")
                                        .country("xxx")
                                        .postalCode("postal_code")
                                        .build()
                                )
                                .email("x")
                                .name("x")
                                .phoneNumberHome("x")
                                .phoneNumberMobile("x")
                                .phoneNumberWork("x")
                                .shippingAddress(
                                    ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                                        .address1("address1")
                                        .address2("address2")
                                        .address3("address3")
                                        .city("city")
                                        .country("xxx")
                                        .postalCode("postal_code")
                                        .build()
                                )
                                .build()
                        )
                        .channel(ThreeDSAuthentication.Channel.APP_BASED)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .merchant(
                            ThreeDSAuthentication.Merchant.builder()
                                .riskIndicator(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                                        .deliveryEmailAddress("delivery_email_address")
                                        .deliveryTimeFrame(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .DeliveryTimeFrame
                                                .ELECTRONIC_DELIVERY
                                        )
                                        .giftCardAmount(0L)
                                        .giftCardCount(0L)
                                        .giftCardCurrency("xxx")
                                        .orderAvailability(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .OrderAvailability
                                                .FUTURE_AVAILABILITY
                                        )
                                        .preOrderAvailableDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reorderItems(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .ReorderItems
                                                .FIRST_TIME_ORDERED
                                        )
                                        .shippingMethod(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .ShippingMethod
                                                .DIGITAL_GOODS
                                        )
                                        .build()
                                )
                                .id("id")
                                .country("xxx")
                                .mcc("xxxx")
                                .name("name")
                                .build()
                        )
                        .messageCategory(
                            ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION
                        )
                        .threeDSRequestorChallengeIndicator(
                            ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE
                        )
                        .additionalData(
                            ThreeDSAuthentication.AdditionalData.builder()
                                .networkDecision(
                                    ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK
                                )
                                .networkRiskScore(0L)
                                .build()
                        )
                        .app(
                            ThreeDSAuthentication.App.builder()
                                .device("device")
                                .deviceInfo("device_info")
                                .ip("ip")
                                .latitude(-90.0)
                                .locale("locale")
                                .longitude(-180.0)
                                .os("os")
                                .platform("platform")
                                .screenHeight(0L)
                                .screenWidth(0L)
                                .timeZone("time_zone")
                                .build()
                        )
                        .authenticationRequestType(
                            ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD
                        )
                        .browser(
                            ThreeDSAuthentication.Browser.builder()
                                .acceptHeader("accept_header")
                                .ip("ip")
                                .javaEnabled(true)
                                .javascriptEnabled(true)
                                .language("language")
                                .timeZone("time_zone")
                                .userAgent("user_agent")
                                .build()
                        )
                        .challengeMetadata(
                            ThreeDSAuthentication.ChallengeMetadata.builder()
                                .methodType(
                                    ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP
                                )
                                .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                                .phoneNumber("phone_number")
                                .build()
                        )
                        .challengeOrchestratedBy(
                            ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC
                        )
                        .decisionMadeBy(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .threeRiRequestType(
                            ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION
                        )
                        .transaction(
                            ThreeDSAuthentication.Transaction.builder()
                                .amount(0.0)
                                .cardholderAmount(0.0)
                                .currency("xxx")
                                .currencyExponent(0.0)
                                .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                                .build()
                        )
                        .build()
                )
                .challenge(
                    ThreeDSAuthenticationChallengeWebhookEvent.Challenge.builder()
                        .challengeMethodType(
                            ThreeDSAuthenticationChallengeWebhookEvent.Challenge.ChallengeMethodType
                                .OUT_OF_BAND
                        )
                        .expiryTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .startTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .appRequestorUrl("https://example.com")
                        .build()
                )
                .eventType(
                    ThreeDSAuthenticationChallengeWebhookEvent.EventType
                        .THREE_DS_AUTHENTICATION_CHALLENGE
                )
                .build()

        assertThat(threeDSAuthenticationChallengeWebhookEvent.authenticationObject())
            .isEqualTo(
                ThreeDSAuthentication.builder()
                    .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .accountType(ThreeDSAuthentication.AccountType.CREDIT)
                    .authenticationResult(ThreeDSAuthentication.AuthenticationResult.DECLINE)
                    .cardExpiryCheck(ThreeDSAuthentication.CardExpiryCheck.MATCH)
                    .cardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .cardholder(
                        ThreeDSAuthentication.Cardholder.builder()
                            .addressMatch(true)
                            .addressOnFileMatch(
                                ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH
                            )
                            .billingAddress(
                                ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                                    .address1("address1")
                                    .address2("address2")
                                    .address3("address3")
                                    .city("city")
                                    .country("xxx")
                                    .postalCode("postal_code")
                                    .build()
                            )
                            .email("x")
                            .name("x")
                            .phoneNumberHome("x")
                            .phoneNumberMobile("x")
                            .phoneNumberWork("x")
                            .shippingAddress(
                                ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                                    .address1("address1")
                                    .address2("address2")
                                    .address3("address3")
                                    .city("city")
                                    .country("xxx")
                                    .postalCode("postal_code")
                                    .build()
                            )
                            .build()
                    )
                    .channel(ThreeDSAuthentication.Channel.APP_BASED)
                    .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .merchant(
                        ThreeDSAuthentication.Merchant.builder()
                            .riskIndicator(
                                ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                                    .deliveryEmailAddress("delivery_email_address")
                                    .deliveryTimeFrame(
                                        ThreeDSAuthentication.Merchant.RiskIndicator
                                            .DeliveryTimeFrame
                                            .ELECTRONIC_DELIVERY
                                    )
                                    .giftCardAmount(0L)
                                    .giftCardCount(0L)
                                    .giftCardCurrency("xxx")
                                    .orderAvailability(
                                        ThreeDSAuthentication.Merchant.RiskIndicator
                                            .OrderAvailability
                                            .FUTURE_AVAILABILITY
                                    )
                                    .preOrderAvailableDate(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .reorderItems(
                                        ThreeDSAuthentication.Merchant.RiskIndicator.ReorderItems
                                            .FIRST_TIME_ORDERED
                                    )
                                    .shippingMethod(
                                        ThreeDSAuthentication.Merchant.RiskIndicator.ShippingMethod
                                            .DIGITAL_GOODS
                                    )
                                    .build()
                            )
                            .id("id")
                            .country("xxx")
                            .mcc("xxxx")
                            .name("name")
                            .build()
                    )
                    .messageCategory(
                        ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION
                    )
                    .threeDSRequestorChallengeIndicator(
                        ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE
                    )
                    .additionalData(
                        ThreeDSAuthentication.AdditionalData.builder()
                            .networkDecision(
                                ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK
                            )
                            .networkRiskScore(0L)
                            .build()
                    )
                    .app(
                        ThreeDSAuthentication.App.builder()
                            .device("device")
                            .deviceInfo("device_info")
                            .ip("ip")
                            .latitude(-90.0)
                            .locale("locale")
                            .longitude(-180.0)
                            .os("os")
                            .platform("platform")
                            .screenHeight(0L)
                            .screenWidth(0L)
                            .timeZone("time_zone")
                            .build()
                    )
                    .authenticationRequestType(
                        ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD
                    )
                    .browser(
                        ThreeDSAuthentication.Browser.builder()
                            .acceptHeader("accept_header")
                            .ip("ip")
                            .javaEnabled(true)
                            .javascriptEnabled(true)
                            .language("language")
                            .timeZone("time_zone")
                            .userAgent("user_agent")
                            .build()
                    )
                    .challengeMetadata(
                        ThreeDSAuthentication.ChallengeMetadata.builder()
                            .methodType(ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP)
                            .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                            .phoneNumber("phone_number")
                            .build()
                    )
                    .challengeOrchestratedBy(ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC)
                    .decisionMadeBy(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
                    .threeRiRequestType(
                        ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION
                    )
                    .transaction(
                        ThreeDSAuthentication.Transaction.builder()
                            .amount(0.0)
                            .cardholderAmount(0.0)
                            .currency("xxx")
                            .currencyExponent(0.0)
                            .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                            .build()
                    )
                    .build()
            )
        assertThat(threeDSAuthenticationChallengeWebhookEvent.challenge())
            .isEqualTo(
                ThreeDSAuthenticationChallengeWebhookEvent.Challenge.builder()
                    .challengeMethodType(
                        ThreeDSAuthenticationChallengeWebhookEvent.Challenge.ChallengeMethodType
                            .OUT_OF_BAND
                    )
                    .expiryTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .startTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .appRequestorUrl("https://example.com")
                    .build()
            )
        assertThat(threeDSAuthenticationChallengeWebhookEvent.eventType())
            .isEqualTo(
                ThreeDSAuthenticationChallengeWebhookEvent.EventType
                    .THREE_DS_AUTHENTICATION_CHALLENGE
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val threeDSAuthenticationChallengeWebhookEvent =
            ThreeDSAuthenticationChallengeWebhookEvent.builder()
                .authenticationObject(
                    ThreeDSAuthentication.builder()
                        .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .accountType(ThreeDSAuthentication.AccountType.CREDIT)
                        .authenticationResult(ThreeDSAuthentication.AuthenticationResult.DECLINE)
                        .cardExpiryCheck(ThreeDSAuthentication.CardExpiryCheck.MATCH)
                        .cardToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .cardholder(
                            ThreeDSAuthentication.Cardholder.builder()
                                .addressMatch(true)
                                .addressOnFileMatch(
                                    ThreeDSAuthentication.Cardholder.AddressMatchResult.MATCH
                                )
                                .billingAddress(
                                    ThreeDSAuthentication.Cardholder.BillingAddress.builder()
                                        .address1("address1")
                                        .address2("address2")
                                        .address3("address3")
                                        .city("city")
                                        .country("xxx")
                                        .postalCode("postal_code")
                                        .build()
                                )
                                .email("x")
                                .name("x")
                                .phoneNumberHome("x")
                                .phoneNumberMobile("x")
                                .phoneNumberWork("x")
                                .shippingAddress(
                                    ThreeDSAuthentication.Cardholder.ShippingAddress.builder()
                                        .address1("address1")
                                        .address2("address2")
                                        .address3("address3")
                                        .city("city")
                                        .country("xxx")
                                        .postalCode("postal_code")
                                        .build()
                                )
                                .build()
                        )
                        .channel(ThreeDSAuthentication.Channel.APP_BASED)
                        .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .merchant(
                            ThreeDSAuthentication.Merchant.builder()
                                .riskIndicator(
                                    ThreeDSAuthentication.Merchant.RiskIndicator.builder()
                                        .deliveryEmailAddress("delivery_email_address")
                                        .deliveryTimeFrame(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .DeliveryTimeFrame
                                                .ELECTRONIC_DELIVERY
                                        )
                                        .giftCardAmount(0L)
                                        .giftCardCount(0L)
                                        .giftCardCurrency("xxx")
                                        .orderAvailability(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .OrderAvailability
                                                .FUTURE_AVAILABILITY
                                        )
                                        .preOrderAvailableDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reorderItems(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .ReorderItems
                                                .FIRST_TIME_ORDERED
                                        )
                                        .shippingMethod(
                                            ThreeDSAuthentication.Merchant.RiskIndicator
                                                .ShippingMethod
                                                .DIGITAL_GOODS
                                        )
                                        .build()
                                )
                                .id("id")
                                .country("xxx")
                                .mcc("xxxx")
                                .name("name")
                                .build()
                        )
                        .messageCategory(
                            ThreeDSAuthentication.MessageCategory.NON_PAYMENT_AUTHENTICATION
                        )
                        .threeDSRequestorChallengeIndicator(
                            ThreeDSAuthentication.ThreeDSRequestorChallengeIndicator.NO_PREFERENCE
                        )
                        .additionalData(
                            ThreeDSAuthentication.AdditionalData.builder()
                                .networkDecision(
                                    ThreeDSAuthentication.AdditionalData.NetworkDecision.LOW_RISK
                                )
                                .networkRiskScore(0L)
                                .build()
                        )
                        .app(
                            ThreeDSAuthentication.App.builder()
                                .device("device")
                                .deviceInfo("device_info")
                                .ip("ip")
                                .latitude(-90.0)
                                .locale("locale")
                                .longitude(-180.0)
                                .os("os")
                                .platform("platform")
                                .screenHeight(0L)
                                .screenWidth(0L)
                                .timeZone("time_zone")
                                .build()
                        )
                        .authenticationRequestType(
                            ThreeDSAuthentication.AuthenticationRequestType.ADD_CARD
                        )
                        .browser(
                            ThreeDSAuthentication.Browser.builder()
                                .acceptHeader("accept_header")
                                .ip("ip")
                                .javaEnabled(true)
                                .javascriptEnabled(true)
                                .language("language")
                                .timeZone("time_zone")
                                .userAgent("user_agent")
                                .build()
                        )
                        .challengeMetadata(
                            ThreeDSAuthentication.ChallengeMetadata.builder()
                                .methodType(
                                    ThreeDSAuthentication.ChallengeMetadata.MethodType.SMS_OTP
                                )
                                .status(ThreeDSAuthentication.ChallengeMetadata.Status.SUCCESS)
                                .phoneNumber("phone_number")
                                .build()
                        )
                        .challengeOrchestratedBy(
                            ThreeDSAuthentication.ChallengeOrchestratedBy.LITHIC
                        )
                        .decisionMadeBy(ThreeDSAuthentication.DecisionMadeBy.LITHIC_RULES)
                        .threeRiRequestType(
                            ThreeDSAuthentication.ThreeRiRequestType.ACCOUNT_VERIFICATION
                        )
                        .transaction(
                            ThreeDSAuthentication.Transaction.builder()
                                .amount(0.0)
                                .cardholderAmount(0.0)
                                .currency("xxx")
                                .currencyExponent(0.0)
                                .dateTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .type(ThreeDSAuthentication.Transaction.Type.ACCOUNT_FUNDING)
                                .build()
                        )
                        .build()
                )
                .challenge(
                    ThreeDSAuthenticationChallengeWebhookEvent.Challenge.builder()
                        .challengeMethodType(
                            ThreeDSAuthenticationChallengeWebhookEvent.Challenge.ChallengeMethodType
                                .OUT_OF_BAND
                        )
                        .expiryTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .startTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .appRequestorUrl("https://example.com")
                        .build()
                )
                .eventType(
                    ThreeDSAuthenticationChallengeWebhookEvent.EventType
                        .THREE_DS_AUTHENTICATION_CHALLENGE
                )
                .build()

        val roundtrippedThreeDSAuthenticationChallengeWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(threeDSAuthenticationChallengeWebhookEvent),
                jacksonTypeRef<ThreeDSAuthenticationChallengeWebhookEvent>(),
            )

        assertThat(roundtrippedThreeDSAuthenticationChallengeWebhookEvent)
            .isEqualTo(threeDSAuthenticationChallengeWebhookEvent)
    }
}
