// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TokenizationApprovalRequestWebhookEventTest {

    @Test
    fun create() {
        val tokenizationApprovalRequestWebhookEvent =
            TokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerTokenizationDecision(
                    TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision.builder()
                        .outcome(
                            TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .eventType(
                    TokenizationApprovalRequestWebhookEvent.EventType.TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(TokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED)
                .tokenMetadata(
                    TokenMetadata.builder()
                        .paymentAccountInfo(
                            TokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_reference")
                                .paymentAccountReference("payment_account_reference")
                                .tokenUniqueReference("token_unique_reference")
                                .build()
                        )
                        .status("status")
                        .paymentAppInstanceId("payment_app_instance_id")
                        .tokenRequestorId("xxxxxxxxxxx")
                        .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .tokenizationChannel(
                    TokenizationApprovalRequestWebhookEvent.TokenizationChannel.DIGITAL_WALLET
                )
                .tokenizationToken("tokenization_token")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("string")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .explanation("explanation")
                        .name("name")
                        .result(TokenizationRuleResult.Result.APPROVED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    TokenizationApprovalRequestWebhookEvent.TokenizationSource.PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        assertThat(tokenizationApprovalRequestWebhookEvent.accountToken())
            .isEqualTo("00000000-0000-0000-0000-000000000002")
        assertThat(tokenizationApprovalRequestWebhookEvent.cardToken())
            .isEqualTo("00000000-0000-0000-0000-000000000001")
        assertThat(tokenizationApprovalRequestWebhookEvent.created())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(tokenizationApprovalRequestWebhookEvent.customerTokenizationDecision())
            .contains(
                TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision.builder()
                    .outcome(
                        TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision.Outcome
                            .APPROVED
                    )
                    .responderUrl("https://example.com")
                    .latency("100")
                    .responseCode("123456")
                    .build()
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.eventType())
            .isEqualTo(
                TokenizationApprovalRequestWebhookEvent.EventType.TOKENIZATION_APPROVAL_REQUEST
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.issuerDecision())
            .isEqualTo(TokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED)
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenMetadata())
            .isEqualTo(
                TokenMetadata.builder()
                    .paymentAccountInfo(
                        TokenMetadata.PaymentAccountInfo.builder()
                            .accountHolderData(
                                TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .panUniqueReference("pan_unique_reference")
                            .paymentAccountReference("payment_account_reference")
                            .tokenUniqueReference("token_unique_reference")
                            .build()
                    )
                    .status("status")
                    .paymentAppInstanceId("payment_app_instance_id")
                    .tokenRequestorId("xxxxxxxxxxx")
                    .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                    .build()
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenizationChannel())
            .isEqualTo(TokenizationApprovalRequestWebhookEvent.TokenizationChannel.DIGITAL_WALLET)
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenizationToken())
            .isEqualTo("tokenization_token")
        assertThat(tokenizationApprovalRequestWebhookEvent.walletDecisioningInfo())
            .isEqualTo(
                WalletDecisioningInfo.builder()
                    .accountScore("100")
                    .deviceScore("100")
                    .recommendedDecision("Decision1")
                    .addRecommendationReason("string")
                    .build()
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.device())
            .contains(
                Device.builder()
                    .imei("123456789012345")
                    .ipAddress("1.1.1.1")
                    .location("37.3860517/-122.0838511")
                    .build()
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.ruleResults().getOrNull())
            .containsExactly(
                TokenizationRuleResult.builder()
                    .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .explanation("explanation")
                    .name("name")
                    .result(TokenizationRuleResult.Result.APPROVED)
                    .build()
            )
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenizationDeclineReasons().getOrNull())
            .containsExactly(TokenizationDeclineReason.ACCOUNT_SCORE_1)
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenizationSource())
            .contains(TokenizationApprovalRequestWebhookEvent.TokenizationSource.PUSH_PROVISION)
        assertThat(tokenizationApprovalRequestWebhookEvent.tokenizationTfaReasons().getOrNull())
            .containsExactly(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val tokenizationApprovalRequestWebhookEvent =
            TokenizationApprovalRequestWebhookEvent.builder()
                .accountToken("00000000-0000-0000-0000-000000000002")
                .cardToken("00000000-0000-0000-0000-000000000001")
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerTokenizationDecision(
                    TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision.builder()
                        .outcome(
                            TokenizationApprovalRequestWebhookEvent.CustomerTokenizationDecision
                                .Outcome
                                .APPROVED
                        )
                        .responderUrl("https://example.com")
                        .latency("100")
                        .responseCode("123456")
                        .build()
                )
                .eventType(
                    TokenizationApprovalRequestWebhookEvent.EventType.TOKENIZATION_APPROVAL_REQUEST
                )
                .issuerDecision(TokenizationApprovalRequestWebhookEvent.IssuerDecision.APPROVED)
                .tokenMetadata(
                    TokenMetadata.builder()
                        .paymentAccountInfo(
                            TokenMetadata.PaymentAccountInfo.builder()
                                .accountHolderData(
                                    TokenMetadata.PaymentAccountInfo.AccountHolderData.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .panUniqueReference("pan_unique_reference")
                                .paymentAccountReference("payment_account_reference")
                                .tokenUniqueReference("token_unique_reference")
                                .build()
                        )
                        .status("status")
                        .paymentAppInstanceId("payment_app_instance_id")
                        .tokenRequestorId("xxxxxxxxxxx")
                        .tokenRequestorName(TokenMetadata.TokenRequestorName.APPLE_PAY)
                        .build()
                )
                .tokenizationChannel(
                    TokenizationApprovalRequestWebhookEvent.TokenizationChannel.DIGITAL_WALLET
                )
                .tokenizationToken("tokenization_token")
                .walletDecisioningInfo(
                    WalletDecisioningInfo.builder()
                        .accountScore("100")
                        .deviceScore("100")
                        .recommendedDecision("Decision1")
                        .addRecommendationReason("string")
                        .build()
                )
                .device(
                    Device.builder()
                        .imei("123456789012345")
                        .ipAddress("1.1.1.1")
                        .location("37.3860517/-122.0838511")
                        .build()
                )
                .addRuleResult(
                    TokenizationRuleResult.builder()
                        .authRuleToken("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .explanation("explanation")
                        .name("name")
                        .result(TokenizationRuleResult.Result.APPROVED)
                        .build()
                )
                .addTokenizationDeclineReason(TokenizationDeclineReason.ACCOUNT_SCORE_1)
                .tokenizationSource(
                    TokenizationApprovalRequestWebhookEvent.TokenizationSource.PUSH_PROVISION
                )
                .addTokenizationTfaReason(TokenizationTfaReason.WALLET_RECOMMENDED_TFA)
                .build()

        val roundtrippedTokenizationApprovalRequestWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(tokenizationApprovalRequestWebhookEvent),
                jacksonTypeRef<TokenizationApprovalRequestWebhookEvent>(),
            )

        assertThat(roundtrippedTokenizationApprovalRequestWebhookEvent)
            .isEqualTo(tokenizationApprovalRequestWebhookEvent)
    }
}
