// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.lithic.api.core.jsonMapper
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TransferLimitsResponseTest {

    @Test
    fun create() {
        val transferLimitsResponse =
            TransferLimitsResponse.builder()
                .addData(
                    TransferLimitsResponse.TransferLimitItem.builder()
                        .companyId("company_id")
                        .dailyLimit(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .date(LocalDate.parse("2019-12-27"))
                        .isFbo(true)
                        .monthlyLimit(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .programLimitPerTransaction(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hasMore(true)
                .build()

        assertThat(transferLimitsResponse.data())
            .containsExactly(
                TransferLimitsResponse.TransferLimitItem.builder()
                    .companyId("company_id")
                    .dailyLimit(
                        TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                            .credit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .debit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .build()
                    )
                    .date(LocalDate.parse("2019-12-27"))
                    .isFbo(true)
                    .monthlyLimit(
                        TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                            .credit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .debit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .build()
                    )
                    .programLimitPerTransaction(
                        TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                            .credit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .debit(
                                TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                    .LimitWithProgress
                                    .builder()
                                    .limit(0L)
                                    .amountOriginated(0L)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(transferLimitsResponse.hasMore()).isEqualTo(true)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val transferLimitsResponse =
            TransferLimitsResponse.builder()
                .addData(
                    TransferLimitsResponse.TransferLimitItem.builder()
                        .companyId("company_id")
                        .dailyLimit(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .date(LocalDate.parse("2019-12-27"))
                        .isFbo(true)
                        .monthlyLimit(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .programLimitPerTransaction(
                            TransferLimitsResponse.TransferLimitItem.DirectionalLimits.builder()
                                .credit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .debit(
                                    TransferLimitsResponse.TransferLimitItem.DirectionalLimits
                                        .LimitWithProgress
                                        .builder()
                                        .limit(0L)
                                        .amountOriginated(0L)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .hasMore(true)
                .build()

        val roundtrippedTransferLimitsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(transferLimitsResponse),
                jacksonTypeRef<TransferLimitsResponse>(),
            )

        assertThat(roundtrippedTransferLimitsResponse).isEqualTo(transferLimitsResponse)
    }
}
