// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class V2ApplyResponseTest {

    @Test
    fun createV2ApplyResponse() {
        val v2ApplyResponse =
            V2ApplyResponse.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .cardTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .currentVersion(
                    V2ApplyResponse.CurrentVersion.builder()
                        .parameters(
                            V2ApplyResponse.CurrentVersion.AuthRuleParameters
                                .ofConditionalBlockParameters(
                                    V2ApplyResponse.CurrentVersion.AuthRuleParameters
                                        .ConditionalBlockParameters
                                        .builder()
                                        .conditions(
                                            listOf(
                                                V2ApplyResponse.CurrentVersion.AuthRuleParameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .builder()
                                                    .attribute(
                                                        V2ApplyResponse.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Attribute
                                                            .MCC
                                                    )
                                                    .operation(
                                                        V2ApplyResponse.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Operation
                                                            .IS_ONE_OF
                                                    )
                                                    .value(
                                                        V2ApplyResponse.CurrentVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Value
                                                            .ofString("string")
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                        )
                        .version(123L)
                        .build()
                )
                .draftVersion(
                    V2ApplyResponse.DraftVersion.builder()
                        .parameters(
                            V2ApplyResponse.DraftVersion.AuthRuleParameters
                                .ofConditionalBlockParameters(
                                    V2ApplyResponse.DraftVersion.AuthRuleParameters
                                        .ConditionalBlockParameters
                                        .builder()
                                        .conditions(
                                            listOf(
                                                V2ApplyResponse.DraftVersion.AuthRuleParameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .builder()
                                                    .attribute(
                                                        V2ApplyResponse.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Attribute
                                                            .MCC
                                                    )
                                                    .operation(
                                                        V2ApplyResponse.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Operation
                                                            .IS_ONE_OF
                                                    )
                                                    .value(
                                                        V2ApplyResponse.DraftVersion
                                                            .AuthRuleParameters
                                                            .ConditionalBlockParameters
                                                            .Condition
                                                            .Value
                                                            .ofString("string")
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                        )
                        .version(123L)
                        .build()
                )
                .programLevel(true)
                .state(V2ApplyResponse.AuthRuleState.ACTIVE)
                .type(V2ApplyResponse.AuthRuleType.CONDITIONAL_BLOCK)
                .build()
        assertThat(v2ApplyResponse).isNotNull
        assertThat(v2ApplyResponse.token()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ApplyResponse.accountTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ApplyResponse.cardTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ApplyResponse.currentVersion())
            .contains(
                V2ApplyResponse.CurrentVersion.builder()
                    .parameters(
                        V2ApplyResponse.CurrentVersion.AuthRuleParameters
                            .ofConditionalBlockParameters(
                                V2ApplyResponse.CurrentVersion.AuthRuleParameters
                                    .ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            V2ApplyResponse.CurrentVersion.AuthRuleParameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    V2ApplyResponse.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    V2ApplyResponse.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    V2ApplyResponse.CurrentVersion
                                                        .AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(v2ApplyResponse.draftVersion())
            .contains(
                V2ApplyResponse.DraftVersion.builder()
                    .parameters(
                        V2ApplyResponse.DraftVersion.AuthRuleParameters
                            .ofConditionalBlockParameters(
                                V2ApplyResponse.DraftVersion.AuthRuleParameters
                                    .ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            V2ApplyResponse.DraftVersion.AuthRuleParameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    V2ApplyResponse.DraftVersion.AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    V2ApplyResponse.DraftVersion.AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    V2ApplyResponse.DraftVersion.AuthRuleParameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(v2ApplyResponse.programLevel()).isEqualTo(true)
        assertThat(v2ApplyResponse.state()).isEqualTo(V2ApplyResponse.AuthRuleState.ACTIVE)
        assertThat(v2ApplyResponse.type()).isEqualTo(V2ApplyResponse.AuthRuleType.CONDITIONAL_BLOCK)
    }
}
