// File generated from our OpenAPI spec by Stainless.

package com.lithic.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class V2ListResponseTest {

    @Test
    fun createV2ListResponse() {
        val v2ListResponse =
            V2ListResponse.builder()
                .token("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .accountTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .cardTokens(listOf("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"))
                .currentVersion(
                    V2ListResponse.CurrentVersion.builder()
                        .parameters(
                            V2ListResponse.CurrentVersion.Parameters.ofConditionalBlockParameters(
                                V2ListResponse.CurrentVersion.Parameters.ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            V2ListResponse.CurrentVersion.Parameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    V2ListResponse.CurrentVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    V2ListResponse.CurrentVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    V2ListResponse.CurrentVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                        )
                        .version(123L)
                        .build()
                )
                .draftVersion(
                    V2ListResponse.DraftVersion.builder()
                        .parameters(
                            V2ListResponse.DraftVersion.Parameters.ofConditionalBlockParameters(
                                V2ListResponse.DraftVersion.Parameters.ConditionalBlockParameters
                                    .builder()
                                    .conditions(
                                        listOf(
                                            V2ListResponse.DraftVersion.Parameters
                                                .ConditionalBlockParameters
                                                .Condition
                                                .builder()
                                                .attribute(
                                                    V2ListResponse.DraftVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Attribute
                                                        .MCC
                                                )
                                                .operation(
                                                    V2ListResponse.DraftVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Operation
                                                        .IS_ONE_OF
                                                )
                                                .value(
                                                    V2ListResponse.DraftVersion.Parameters
                                                        .ConditionalBlockParameters
                                                        .Condition
                                                        .Value
                                                        .ofString("string")
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                        )
                        .version(123L)
                        .build()
                )
                .programLevel(true)
                .state(V2ListResponse.AuthRuleState.ACTIVE)
                .type(V2ListResponse.AuthRuleType.CONDITIONAL_BLOCK)
                .build()
        assertThat(v2ListResponse).isNotNull
        assertThat(v2ListResponse.token()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ListResponse.accountTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ListResponse.cardTokens())
            .containsExactly("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(v2ListResponse.currentVersion())
            .contains(
                V2ListResponse.CurrentVersion.builder()
                    .parameters(
                        V2ListResponse.CurrentVersion.Parameters.ofConditionalBlockParameters(
                            V2ListResponse.CurrentVersion.Parameters.ConditionalBlockParameters
                                .builder()
                                .conditions(
                                    listOf(
                                        V2ListResponse.CurrentVersion.Parameters
                                            .ConditionalBlockParameters
                                            .Condition
                                            .builder()
                                            .attribute(
                                                V2ListResponse.CurrentVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Attribute
                                                    .MCC
                                            )
                                            .operation(
                                                V2ListResponse.CurrentVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Operation
                                                    .IS_ONE_OF
                                            )
                                            .value(
                                                V2ListResponse.CurrentVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Value
                                                    .ofString("string")
                                            )
                                            .build()
                                    )
                                )
                                .build()
                        )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(v2ListResponse.draftVersion())
            .contains(
                V2ListResponse.DraftVersion.builder()
                    .parameters(
                        V2ListResponse.DraftVersion.Parameters.ofConditionalBlockParameters(
                            V2ListResponse.DraftVersion.Parameters.ConditionalBlockParameters
                                .builder()
                                .conditions(
                                    listOf(
                                        V2ListResponse.DraftVersion.Parameters
                                            .ConditionalBlockParameters
                                            .Condition
                                            .builder()
                                            .attribute(
                                                V2ListResponse.DraftVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Attribute
                                                    .MCC
                                            )
                                            .operation(
                                                V2ListResponse.DraftVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Operation
                                                    .IS_ONE_OF
                                            )
                                            .value(
                                                V2ListResponse.DraftVersion.Parameters
                                                    .ConditionalBlockParameters
                                                    .Condition
                                                    .Value
                                                    .ofString("string")
                                            )
                                            .build()
                                    )
                                )
                                .build()
                        )
                    )
                    .version(123L)
                    .build()
            )
        assertThat(v2ListResponse.programLevel()).isEqualTo(true)
        assertThat(v2ListResponse.state()).isEqualTo(V2ListResponse.AuthRuleState.ACTIVE)
        assertThat(v2ListResponse.type()).isEqualTo(V2ListResponse.AuthRuleType.CONDITIONAL_BLOCK)
    }
}
